/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { MiddayError } from "./middayerror.js";

/**
 * Internal server error
 */
export type DownloadFileInternalServerErrorData = {
  error: string;
};

/**
 * Internal server error
 */
export class DownloadFileInternalServerError extends MiddayError {
  error: string;

  /** The original data that was passed to this error instance. */
  data$: DownloadFileInternalServerErrorData;

  constructor(
    err: DownloadFileInternalServerErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "DownloadFileInternalServerError";
  }
}

/**
 * Not found
 */
export type DownloadFileNotFoundErrorData = {
  error: string;
};

/**
 * Not found
 */
export class DownloadFileNotFoundError extends MiddayError {
  error: string;

  /** The original data that was passed to this error instance. */
  data$: DownloadFileNotFoundErrorData;

  constructor(
    err: DownloadFileNotFoundErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "DownloadFileNotFoundError";
  }
}

/**
 * Unauthorized
 */
export type DownloadFileUnauthorizedErrorData = {
  error: string;
};

/**
 * Unauthorized
 */
export class DownloadFileUnauthorizedError extends MiddayError {
  error: string;

  /** The original data that was passed to this error instance. */
  data$: DownloadFileUnauthorizedErrorData;

  constructor(
    err: DownloadFileUnauthorizedErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "DownloadFileUnauthorizedError";
  }
}

/**
 * Bad request
 */
export type DownloadFileBadRequestErrorData = {
  error: string;
};

/**
 * Bad request
 */
export class DownloadFileBadRequestError extends MiddayError {
  error: string;

  /** The original data that was passed to this error instance. */
  data$: DownloadFileBadRequestErrorData;

  constructor(
    err: DownloadFileBadRequestErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "DownloadFileBadRequestError";
  }
}

/** @internal */
export const DownloadFileInternalServerError$inboundSchema: z.ZodType<
  DownloadFileInternalServerError,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.string(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new DownloadFileInternalServerError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type DownloadFileInternalServerError$Outbound = {
  error: string;
};

/** @internal */
export const DownloadFileInternalServerError$outboundSchema: z.ZodType<
  DownloadFileInternalServerError$Outbound,
  z.ZodTypeDef,
  DownloadFileInternalServerError
> = z.instanceof(DownloadFileInternalServerError)
  .transform(v => v.data$)
  .pipe(z.object({
    error: z.string(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DownloadFileInternalServerError$ {
  /** @deprecated use `DownloadFileInternalServerError$inboundSchema` instead. */
  export const inboundSchema = DownloadFileInternalServerError$inboundSchema;
  /** @deprecated use `DownloadFileInternalServerError$outboundSchema` instead. */
  export const outboundSchema = DownloadFileInternalServerError$outboundSchema;
  /** @deprecated use `DownloadFileInternalServerError$Outbound` instead. */
  export type Outbound = DownloadFileInternalServerError$Outbound;
}

/** @internal */
export const DownloadFileNotFoundError$inboundSchema: z.ZodType<
  DownloadFileNotFoundError,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.string(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new DownloadFileNotFoundError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type DownloadFileNotFoundError$Outbound = {
  error: string;
};

/** @internal */
export const DownloadFileNotFoundError$outboundSchema: z.ZodType<
  DownloadFileNotFoundError$Outbound,
  z.ZodTypeDef,
  DownloadFileNotFoundError
> = z.instanceof(DownloadFileNotFoundError)
  .transform(v => v.data$)
  .pipe(z.object({
    error: z.string(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DownloadFileNotFoundError$ {
  /** @deprecated use `DownloadFileNotFoundError$inboundSchema` instead. */
  export const inboundSchema = DownloadFileNotFoundError$inboundSchema;
  /** @deprecated use `DownloadFileNotFoundError$outboundSchema` instead. */
  export const outboundSchema = DownloadFileNotFoundError$outboundSchema;
  /** @deprecated use `DownloadFileNotFoundError$Outbound` instead. */
  export type Outbound = DownloadFileNotFoundError$Outbound;
}

/** @internal */
export const DownloadFileUnauthorizedError$inboundSchema: z.ZodType<
  DownloadFileUnauthorizedError,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.string(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new DownloadFileUnauthorizedError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type DownloadFileUnauthorizedError$Outbound = {
  error: string;
};

/** @internal */
export const DownloadFileUnauthorizedError$outboundSchema: z.ZodType<
  DownloadFileUnauthorizedError$Outbound,
  z.ZodTypeDef,
  DownloadFileUnauthorizedError
> = z.instanceof(DownloadFileUnauthorizedError)
  .transform(v => v.data$)
  .pipe(z.object({
    error: z.string(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DownloadFileUnauthorizedError$ {
  /** @deprecated use `DownloadFileUnauthorizedError$inboundSchema` instead. */
  export const inboundSchema = DownloadFileUnauthorizedError$inboundSchema;
  /** @deprecated use `DownloadFileUnauthorizedError$outboundSchema` instead. */
  export const outboundSchema = DownloadFileUnauthorizedError$outboundSchema;
  /** @deprecated use `DownloadFileUnauthorizedError$Outbound` instead. */
  export type Outbound = DownloadFileUnauthorizedError$Outbound;
}

/** @internal */
export const DownloadFileBadRequestError$inboundSchema: z.ZodType<
  DownloadFileBadRequestError,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.string(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new DownloadFileBadRequestError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type DownloadFileBadRequestError$Outbound = {
  error: string;
};

/** @internal */
export const DownloadFileBadRequestError$outboundSchema: z.ZodType<
  DownloadFileBadRequestError$Outbound,
  z.ZodTypeDef,
  DownloadFileBadRequestError
> = z.instanceof(DownloadFileBadRequestError)
  .transform(v => v.data$)
  .pipe(z.object({
    error: z.string(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DownloadFileBadRequestError$ {
  /** @deprecated use `DownloadFileBadRequestError$inboundSchema` instead. */
  export const inboundSchema = DownloadFileBadRequestError$inboundSchema;
  /** @deprecated use `DownloadFileBadRequestError$outboundSchema` instead. */
  export const outboundSchema = DownloadFileBadRequestError$outboundSchema;
  /** @deprecated use `DownloadFileBadRequestError$Outbound` instead. */
  export type Outbound = DownloadFileBadRequestError$Outbound;
}
