/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import * as operations from "../operations/index.js";
import { MiddayError } from "./middayerror.js";

/**
 * Internal server error
 */
export type InboxWebhookInternalServerErrorData = {
  error: string;
};

/**
 * Internal server error
 */
export class InboxWebhookInternalServerError extends MiddayError {
  error: string;

  /** The original data that was passed to this error instance. */
  data$: InboxWebhookInternalServerErrorData;

  constructor(
    err: InboxWebhookInternalServerErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;

    this.name = "InboxWebhookInternalServerError";
  }
}

/**
 * Invalid request
 */
export type InboxWebhookBadRequestErrorData = {
  error: string;
  errors?: Array<operations.ErrorT> | undefined;
};

/**
 * Invalid request
 */
export class InboxWebhookBadRequestError extends MiddayError {
  error: string;
  errors?: Array<operations.ErrorT> | undefined;

  /** The original data that was passed to this error instance. */
  data$: InboxWebhookBadRequestErrorData;

  constructor(
    err: InboxWebhookBadRequestErrorData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;
    if (err.errors != null) this.errors = err.errors;

    this.name = "InboxWebhookBadRequestError";
  }
}

/** @internal */
export const InboxWebhookInternalServerError$inboundSchema: z.ZodType<
  InboxWebhookInternalServerError,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.string(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new InboxWebhookInternalServerError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type InboxWebhookInternalServerError$Outbound = {
  error: string;
};

/** @internal */
export const InboxWebhookInternalServerError$outboundSchema: z.ZodType<
  InboxWebhookInternalServerError$Outbound,
  z.ZodTypeDef,
  InboxWebhookInternalServerError
> = z.instanceof(InboxWebhookInternalServerError)
  .transform(v => v.data$)
  .pipe(z.object({
    error: z.string(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace InboxWebhookInternalServerError$ {
  /** @deprecated use `InboxWebhookInternalServerError$inboundSchema` instead. */
  export const inboundSchema = InboxWebhookInternalServerError$inboundSchema;
  /** @deprecated use `InboxWebhookInternalServerError$outboundSchema` instead. */
  export const outboundSchema = InboxWebhookInternalServerError$outboundSchema;
  /** @deprecated use `InboxWebhookInternalServerError$Outbound` instead. */
  export type Outbound = InboxWebhookInternalServerError$Outbound;
}

/** @internal */
export const InboxWebhookBadRequestError$inboundSchema: z.ZodType<
  InboxWebhookBadRequestError,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.string(),
  errors: z.array(z.lazy(() => operations.ErrorT$inboundSchema)).optional(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    return new InboxWebhookBadRequestError(v, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type InboxWebhookBadRequestError$Outbound = {
  error: string;
  errors?: Array<operations.ErrorT$Outbound> | undefined;
};

/** @internal */
export const InboxWebhookBadRequestError$outboundSchema: z.ZodType<
  InboxWebhookBadRequestError$Outbound,
  z.ZodTypeDef,
  InboxWebhookBadRequestError
> = z.instanceof(InboxWebhookBadRequestError)
  .transform(v => v.data$)
  .pipe(z.object({
    error: z.string(),
    errors: z.array(z.lazy(() => operations.ErrorT$outboundSchema)).optional(),
  }));

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace InboxWebhookBadRequestError$ {
  /** @deprecated use `InboxWebhookBadRequestError$inboundSchema` instead. */
  export const inboundSchema = InboxWebhookBadRequestError$inboundSchema;
  /** @deprecated use `InboxWebhookBadRequestError$outboundSchema` instead. */
  export const outboundSchema = InboxWebhookBadRequestError$outboundSchema;
  /** @deprecated use `InboxWebhookBadRequestError$Outbound` instead. */
  export type Outbound = InboxWebhookBadRequestError$Outbound;
}
