/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { MiddayError } from "./middayerror.js";

export type OAuthErrorResponseData = {
  /**
   * Error code
   */
  error: string;
  /**
   * Human-readable error description
   */
  errorDescription?: string | undefined;
  /**
   * URI to a human-readable error page
   */
  errorUri?: string | undefined;
  /**
   * Opaque state parameter from the original request
   */
  state?: string | undefined;
};

export class OAuthErrorResponse extends MiddayError {
  /**
   * Error code
   */
  error: string;
  /**
   * Human-readable error description
   */
  errorDescription?: string | undefined;
  /**
   * URI to a human-readable error page
   */
  errorUri?: string | undefined;
  /**
   * Opaque state parameter from the original request
   */
  state?: string | undefined;

  /** The original data that was passed to this error instance. */
  data$: OAuthErrorResponseData;

  constructor(
    err: OAuthErrorResponseData,
    httpMeta: { response: Response; request: Request; body: string },
  ) {
    const message = "message" in err && typeof err.message === "string"
      ? err.message
      : `API error occurred: ${JSON.stringify(err)}`;
    super(message, httpMeta);
    this.data$ = err;
    this.error = err.error;
    if (err.errorDescription != null) {
      this.errorDescription = err.errorDescription;
    }
    if (err.errorUri != null) this.errorUri = err.errorUri;
    if (err.state != null) this.state = err.state;

    this.name = "OAuthErrorResponse";
  }
}

/** @internal */
export const OAuthErrorResponse$inboundSchema: z.ZodType<
  OAuthErrorResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  error: z.string(),
  error_description: z.string().optional(),
  error_uri: z.string().optional(),
  state: z.string().optional(),
  request$: z.instanceof(Request),
  response$: z.instanceof(Response),
  body$: z.string(),
})
  .transform((v) => {
    const remapped = remap$(v, {
      "error_description": "errorDescription",
      "error_uri": "errorUri",
    });

    return new OAuthErrorResponse(remapped, {
      request: v.request$,
      response: v.response$,
      body: v.body$,
    });
  });

/** @internal */
export type OAuthErrorResponse$Outbound = {
  error: string;
  error_description?: string | undefined;
  error_uri?: string | undefined;
  state?: string | undefined;
};

/** @internal */
export const OAuthErrorResponse$outboundSchema: z.ZodType<
  OAuthErrorResponse$Outbound,
  z.ZodTypeDef,
  OAuthErrorResponse
> = z.instanceof(OAuthErrorResponse)
  .transform(v => v.data$)
  .pipe(
    z.object({
      error: z.string(),
      errorDescription: z.string().optional(),
      errorUri: z.string().optional(),
      state: z.string().optional(),
    }).transform((v) => {
      return remap$(v, {
        errorDescription: "error_description",
        errorUri: "error_uri",
      });
    }),
  );

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace OAuthErrorResponse$ {
  /** @deprecated use `OAuthErrorResponse$inboundSchema` instead. */
  export const inboundSchema = OAuthErrorResponse$inboundSchema;
  /** @deprecated use `OAuthErrorResponse$outboundSchema` instead. */
  export const outboundSchema = OAuthErrorResponse$outboundSchema;
  /** @deprecated use `OAuthErrorResponse$Outbound` instead. */
  export type Outbound = OAuthErrorResponse$Outbound;
}
