/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { bankAccountsList } from "../../funcs/bankAccountsList.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.ListBankAccountsRequest$inboundSchema,
};

export const tool$bankAccountsList: ToolDefinition<typeof args> = {
  name: "bank-accounts-list",
  description: `List all bank accounts

Retrieve a list of bank accounts for the authenticated team.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await bankAccountsList(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
