/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { bankAccountsDelete } from "../../funcs/bankAccountsDelete.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.DeleteBankAccountRequest$inboundSchema,
};

export const tool$bankAccountsDelete: ToolDefinition<typeof args> = {
  name: "bank-accounts-delete",
  description: `Delete a bank account

Delete a bank account by ID for the authenticated team.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await bankAccountsDelete(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
