/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { customersPostV1Customers } from "../../funcs/customersPostV1Customers.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.PostV1CustomersRequest$inboundSchema.optional(),
};

export const tool$customersPostV1Customers: ToolDefinition<typeof args> = {
  name: "customers-post-v1-customers",
  description: `Create customer

Create a new customer for the authenticated team.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await customersPostV1Customers(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
