/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { desktopCheckUpdate } from "../../funcs/desktopCheckUpdate.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$desktopCheckUpdate: ToolDefinition = {
  name: "desktop-check-update",
  description: `Check for desktop app updates

Returns the latest desktop app version info in Tauri updater format. Download URLs are rewritten to proxy through this API.`,
  tool: async (client, ctx) => {
    const [result, apiCall] = await desktopCheckUpdate(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
