/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { inboxDeleteV1InboxId } from "../../funcs/inboxDeleteV1InboxId.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.DeleteV1InboxIdRequest$inboundSchema,
};

export const tool$inboxDeleteV1InboxId: ToolDefinition<typeof args> = {
  name: "inbox-delete-v1-inbox-id",
  description: `Delete a inbox item

Delete a inbox item by its unique identifier for the authenticated team.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await inboxDeleteV1InboxId(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
