/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { integrationsOutlookOAuthCallback } from "../../funcs/integrationsOutlookOAuthCallback.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.OutlookOAuthCallbackRequest$inboundSchema,
};

export const tool$integrationsOutlookOAuthCallback: ToolDefinition<
  typeof args
> = {
  name: "integrations-outlook-O-auth-callback",
  description: `Outlook OAuth callback

Handles OAuth callback from Microsoft after user authorization. Exchanges authorization code for access token and creates inbox account.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await integrationsOutlookOAuthCallback(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
