/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { integrationsXeroOAuthCallback } from "../../funcs/integrationsXeroOAuthCallback.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.XeroOAuthCallbackRequest$inboundSchema,
};

export const tool$integrationsXeroOAuthCallback: ToolDefinition<typeof args> = {
  name: "integrations-xero-O-auth-callback",
  description: `Xero OAuth callback

Handles OAuth callback from Xero after user authorization. Exchanges authorization code for access token and creates app integration.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await integrationsXeroOAuthCallback(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
