/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { integrationsSlackWebhook } from "../../funcs/integrationsSlackWebhook.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$integrationsSlackWebhook: ToolDefinition = {
  name: "integrations-slack-webhook",
  description: `Slack webhook handler

Handles incoming webhook events from Slack. Verifies request signature and processes events.`,
  tool: async (client, ctx) => {
    const [result, apiCall] = await integrationsSlackWebhook(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
