/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { invoicesGet } from "../../funcs/invoicesGet.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetInvoiceByIdRequest$inboundSchema,
};

export const tool$invoicesGet: ToolDefinition<typeof args> = {
  name: "invoices-get",
  description: `Retrieve a invoice

Retrieve a invoice by its unique identifier for the authenticated team.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await invoicesGet(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
