/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { invoicesPaymentStatus } from "../../funcs/invoicesPaymentStatus.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$invoicesPaymentStatus: ToolDefinition = {
  name: "invoices-payment-status",
  description: `Payment status

Get payment status for the authenticated team.`,
  tool: async (client, ctx) => {
    const [result, apiCall] = await invoicesPaymentStatus(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
