/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { invoicesGetV1InvoicesId } from "../../funcs/invoicesGetV1InvoicesId.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetV1InvoicesIdRequest$inboundSchema,
};

export const tool$invoicesGetV1InvoicesId: ToolDefinition<typeof args> = {
  name: "invoices-get-v1-invoices-id",
  description: `Retrieve a invoice

Retrieve a invoice by its unique identifier for the authenticated team.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await invoicesGetV1InvoicesId(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
