/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { invoicesSummary } from "../../funcs/invoicesSummary.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetInvoiceSummaryRequest$inboundSchema,
};

export const tool$invoicesSummary: ToolDefinition<typeof args> = {
  name: "invoices-summary",
  description: `Invoice summary

Get summary of invoices for the authenticated team.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await invoicesSummary(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
