/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { invoicePaymentsStripeConnectCallback } from "../../funcs/invoicePaymentsStripeConnectCallback.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.StripeConnectCallbackRequest$inboundSchema,
};

export const tool$invoicePaymentsStripeConnectCallback: ToolDefinition<
  typeof args
> = {
  name: "invoice-payments-stripe-connect-callback",
  description: `Stripe Connect OAuth callback

Handles OAuth callback from Stripe Connect after user authorization. Exchanges authorization code for connected account ID.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await invoicePaymentsStripeConnectCallback(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
