/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { invoicesUpdate } from "../../funcs/invoicesUpdate.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.UpdateInvoiceRequest$inboundSchema,
};

export const tool$invoicesUpdate: ToolDefinition<typeof args> = {
  name: "invoices-update",
  description: `Update an invoice

Update an invoice by its unique identifier for the authenticated team.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await invoicesUpdate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
