/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { metricsGetV1MetricsRevenue } from "../../funcs/metricsGetV1MetricsRevenue.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetV1MetricsRevenueRequest$inboundSchema,
};

export const tool$metricsGetV1MetricsRevenue: ToolDefinition<typeof args> = {
  name: "metrics-get-v1-metrics-revenue",
  description: `Revenue metrics

Revenue metrics for the authenticated team.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await metricsGetV1MetricsRevenue(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
