/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { metricsProfit } from "../../funcs/metricsProfit.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetProfitMetricsRequest$inboundSchema,
};

export const tool$metricsProfit: ToolDefinition<typeof args> = {
  name: "metrics-profit",
  description: `Profit metrics

Profit metrics for the authenticated team.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await metricsProfit(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
