/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { metricsBurnRate } from "../../funcs/metricsBurnRate.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetBurnRateMetricsRequest$inboundSchema,
};

export const tool$metricsBurnRate: ToolDefinition<typeof args> = {
  name: "metrics-burn-rate",
  description: `Burn rate metrics

Burn rate metrics for the authenticated team.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await metricsBurnRate(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
