/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { notificationsUpdateStatus } from "../../funcs/notificationsUpdateStatus.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.UpdateNotificationStatusRequest$inboundSchema,
};

export const tool$notificationsUpdateStatus: ToolDefinition<typeof args> = {
  name: "notifications-update-status",
  description: `Update notification status

Update the status of a specific notification.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await notificationsUpdateStatus(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
