/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { notificationsList } from "../../funcs/notificationsList.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.ListNotificationsRequest$inboundSchema,
};

export const tool$notificationsList: ToolDefinition<typeof args> = {
  name: "notifications-list",
  description: `List all notifications

Retrieve a list of notifications for the authenticated team.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await notificationsList(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
