/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { reportsProfit } from "../../funcs/reportsProfit.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetProfitReportsRequest$inboundSchema,
};

export const tool$reportsProfit: ToolDefinition<typeof args> = {
  name: "reports-profit",
  description: `Profit reports

Profit reports for the authenticated team.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await reportsProfit(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
