/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { reportsExpenses } from "../../funcs/reportsExpenses.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetExpensesReportsRequest$inboundSchema,
};

export const tool$reportsExpenses: ToolDefinition<typeof args> = {
  name: "reports-expenses",
  description: `Expense reports

Expense reports for the authenticated team.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await reportsExpenses(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
