/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { searchGetV1Search } from "../../funcs/searchGetV1Search.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetV1SearchRequest$inboundSchema,
};

export const tool$searchGetV1Search: ToolDefinition<typeof args> = {
  name: "search-get-v1-search",
  description: `Search

Search across all data, invoices, documents, customers, transactions, and more.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await searchGetV1Search(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
