/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { tagsPostV1Tags } from "../../funcs/tagsPostV1Tags.js";
import * as models from "../../models/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: models.CreateTag$inboundSchema.optional(),
};

export const tool$tagsPostV1Tags: ToolDefinition<typeof args> = {
  name: "tags-post-v1-tags",
  description: `Create a new tag

Create a new tag for the authenticated team.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await tagsPostV1Tags(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
