/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { tagsGetV1TagsId } from "../../funcs/tagsGetV1TagsId.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetV1TagsIdRequest$inboundSchema,
};

export const tool$tagsGetV1TagsId: ToolDefinition<typeof args> = {
  name: "tags-get-v1-tags-id",
  description: `Retrieve a tag

Retrieve a tag by ID for the authenticated team.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await tagsGetV1TagsId(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
