/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { teamsGetV1TeamsIdMembers } from "../../funcs/teamsGetV1TeamsIdMembers.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetV1TeamsIdMembersRequest$inboundSchema,
};

export const tool$teamsGetV1TeamsIdMembers: ToolDefinition<typeof args> = {
  name: "teams-get-v1-teams-id-members",
  description: `List all team members

List all team members for the authenticated team.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await teamsGetV1TeamsIdMembers(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
