/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { trackerDeleteV1TrackerProjectsId } from "../../funcs/trackerDeleteV1TrackerProjectsId.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.DeleteV1TrackerProjectsIdRequest$inboundSchema,
};

export const tool$trackerDeleteV1TrackerProjectsId: ToolDefinition<
  typeof args
> = {
  name: "tracker-delete-v1-tracker-projects-id",
  description: `Delete a tracker project

Delete a tracker project for the authenticated team.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await trackerDeleteV1TrackerProjectsId(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
