/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { trackerPostV1TrackerProjects } from "../../funcs/trackerPostV1TrackerProjects.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.PostV1TrackerProjectsRequest$inboundSchema.optional(),
};

export const tool$trackerPostV1TrackerProjects: ToolDefinition<typeof args> = {
  name: "tracker-post-v1-tracker-projects",
  description: `Create a tracker project

Create a tracker project for the authenticated team.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await trackerPostV1TrackerProjects(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
