/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { trackerProjectsGet } from "../../funcs/trackerProjectsGet.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.GetTrackerProjectByIdRequest$inboundSchema,
};

export const tool$trackerProjectsGet: ToolDefinition<typeof args> = {
  name: "tracker-projects-get",
  description: `Retrieve a tracker project

Retrieve a tracker project for the authenticated team.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await trackerProjectsGet(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
