/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { trackerEntriesList } from "../../funcs/trackerEntriesList.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.ListTrackerEntriesRequest$inboundSchema,
};

export const tool$trackerEntriesList: ToolDefinition<typeof args> = {
  name: "tracker-entries-list",
  description: `List all tracker entries

List all tracker entries for the authenticated team.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await trackerEntriesList(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
