/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { transactionsDeleteMany } from "../../funcs/transactionsDeleteMany.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: z.array(z.string()).optional(),
};

export const tool$transactionsDeleteMany: ToolDefinition<typeof args> = {
  name: "transactions-delete-many",
  description: `Bulk delete transactions

Bulk delete transactions for the authenticated team. Only manually created transactions can be deleted via this endpoint or the form. Transactions inserted by bank connections cannot be deleted, but can be excluded by updating the status.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await transactionsDeleteMany(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
