/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { webhooksWhatsappWebhook } from "../../funcs/webhooksWhatsappWebhook.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: z.nullable(z.any()).optional(),
};

export const tool$webhooksWhatsappWebhook: ToolDefinition<typeof args> = {
  name: "webhooks-whatsapp-webhook",
  description: `WhatsApp webhook

Receive messages, media, and button replies from WhatsApp Business API`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await webhooksWhatsappWebhook(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
