/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { webhooksPolarWebhook } from "../../funcs/webhooksPolarWebhook.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$webhooksPolarWebhook: ToolDefinition = {
  name: "webhooks-polar-webhook",
  description: `Polar webhook handler

Handles Polar webhook events for subscription changes. Verifies webhook signature and processes subscription events.`,
  tool: async (client, ctx) => {
    const [result, apiCall] = await webhooksPolarWebhook(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
