/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { MiddayCore } from "../core.js";
import { SDKOptions } from "../lib/config.js";
import type { ConsoleLogger } from "./console-logger.js";
import { createRegisterPrompt } from "./prompts.js";
import {
  createRegisterResource,
  createRegisterResourceTemplate,
} from "./resources.js";
import { MCPScope } from "./scopes.js";
import { createRegisterTool } from "./tools.js";
import { tool$bankAccountsCreate } from "./tools/bankAccountsCreate.js";
import { tool$bankAccountsDelete } from "./tools/bankAccountsDelete.js";
import { tool$bankAccountsGet } from "./tools/bankAccountsGet.js";
import { tool$bankAccountsList } from "./tools/bankAccountsList.js";
import { tool$bankAccountsUpdate } from "./tools/bankAccountsUpdate.js";
import { tool$customersCreate } from "./tools/customersCreate.js";
import { tool$customersDelete } from "./tools/customersDelete.js";
import { tool$customersGet } from "./tools/customersGet.js";
import { tool$customersList } from "./tools/customersList.js";
import { tool$customersUpdate } from "./tools/customersUpdate.js";
import { tool$documentsDelete } from "./tools/documentsDelete.js";
import { tool$documentsGet } from "./tools/documentsGet.js";
import { tool$documentsList } from "./tools/documentsList.js";
import { tool$inboxDelete } from "./tools/inboxDelete.js";
import { tool$inboxGet } from "./tools/inboxGet.js";
import { tool$inboxList } from "./tools/inboxList.js";
import { tool$inboxUpdate } from "./tools/inboxUpdate.js";
import { tool$invoicesDelete } from "./tools/invoicesDelete.js";
import { tool$invoicesGet } from "./tools/invoicesGet.js";
import { tool$invoicesGetInvoicesPaymentStatus } from "./tools/invoicesGetInvoicesPaymentStatus.js";
import { tool$invoicesList } from "./tools/invoicesList.js";
import { tool$invoicesSummary } from "./tools/invoicesSummary.js";
import { tool$metricsBurnRate } from "./tools/metricsBurnRate.js";
import { tool$metricsExpenses } from "./tools/metricsExpenses.js";
import { tool$metricsProfit } from "./tools/metricsProfit.js";
import { tool$metricsRevenue } from "./tools/metricsRevenue.js";
import { tool$metricsRunway } from "./tools/metricsRunway.js";
import { tool$metricsSpending } from "./tools/metricsSpending.js";
import { tool$searchSearch } from "./tools/searchSearch.js";
import { tool$tagsCreate } from "./tools/tagsCreate.js";
import { tool$tagsDelete } from "./tools/tagsDelete.js";
import { tool$tagsGet } from "./tools/tagsGet.js";
import { tool$tagsList } from "./tools/tagsList.js";
import { tool$tagsUpdate } from "./tools/tagsUpdate.js";
import { tool$teamsGet } from "./tools/teamsGet.js";
import { tool$teamsList } from "./tools/teamsList.js";
import { tool$teamsMembers } from "./tools/teamsMembers.js";
import { tool$teamsUpdate } from "./tools/teamsUpdate.js";
import { tool$trackerDelete } from "./tools/trackerDelete.js";
import { tool$trackerEntriesList } from "./tools/trackerEntriesList.js";
import { tool$trackerProjectsCreate } from "./tools/trackerProjectsCreate.js";
import { tool$trackerProjectsDelete } from "./tools/trackerProjectsDelete.js";
import { tool$trackerProjectsGet } from "./tools/trackerProjectsGet.js";
import { tool$trackerProjectsList } from "./tools/trackerProjectsList.js";
import { tool$trackerProjectsUpdate } from "./tools/trackerProjectsUpdate.js";
import { tool$transactionsCreate } from "./tools/transactionsCreate.js";
import { tool$transactionsCreateMany } from "./tools/transactionsCreateMany.js";
import { tool$transactionsDelete } from "./tools/transactionsDelete.js";
import { tool$transactionsDeleteMany } from "./tools/transactionsDeleteMany.js";
import { tool$transactionsGet } from "./tools/transactionsGet.js";
import { tool$transactionsList } from "./tools/transactionsList.js";
import { tool$transactionsUpdate } from "./tools/transactionsUpdate.js";
import { tool$transactionsUpdateMany } from "./tools/transactionsUpdateMany.js";
import { tool$usersGet } from "./tools/usersGet.js";
import { tool$usersUpdate } from "./tools/usersUpdate.js";

export function createMCPServer(deps: {
  logger: ConsoleLogger;
  allowedTools?: string[] | undefined;
  scopes?: MCPScope[] | undefined;
  serverURL?: string | undefined;
  token?: SDKOptions["token"] | undefined;
  serverIdx?: SDKOptions["serverIdx"] | undefined;
}) {
  const server = new McpServer({
    name: "Midday",
    version: "0.2.3",
  });

  const client = new MiddayCore({
    token: deps.token,
    serverURL: deps.serverURL,
    serverIdx: deps.serverIdx,
  });

  const scopes = new Set(deps.scopes);

  const allowedTools = deps.allowedTools && new Set(deps.allowedTools);
  const tool = createRegisterTool(
    deps.logger,
    server,
    client,
    scopes,
    allowedTools,
  );
  const resource = createRegisterResource(deps.logger, server, client, scopes);
  const resourceTemplate = createRegisterResourceTemplate(
    deps.logger,
    server,
    client,
    scopes,
  );
  const prompt = createRegisterPrompt(deps.logger, server, client, scopes);
  const register = { tool, resource, resourceTemplate, prompt };
  void register; // suppress unused warnings

  tool(tool$transactionsList);
  tool(tool$transactionsCreate);
  tool(tool$transactionsGet);
  tool(tool$transactionsUpdate);
  tool(tool$transactionsDelete);
  tool(tool$transactionsUpdateMany);
  tool(tool$transactionsCreateMany);
  tool(tool$transactionsDeleteMany);
  tool(tool$teamsList);
  tool(tool$teamsGet);
  tool(tool$teamsUpdate);
  tool(tool$teamsMembers);
  tool(tool$usersGet);
  tool(tool$usersUpdate);
  tool(tool$customersList);
  tool(tool$customersCreate);
  tool(tool$customersGet);
  tool(tool$customersUpdate);
  tool(tool$customersDelete);
  tool(tool$bankAccountsList);
  tool(tool$bankAccountsCreate);
  tool(tool$bankAccountsGet);
  tool(tool$bankAccountsUpdate);
  tool(tool$bankAccountsDelete);
  tool(tool$tagsList);
  tool(tool$tagsCreate);
  tool(tool$tagsGet);
  tool(tool$tagsUpdate);
  tool(tool$tagsDelete);
  tool(tool$documentsList);
  tool(tool$documentsGet);
  tool(tool$documentsDelete);
  tool(tool$inboxList);
  tool(tool$inboxGet);
  tool(tool$inboxDelete);
  tool(tool$inboxUpdate);
  tool(tool$invoicesList);
  tool(tool$invoicesGetInvoicesPaymentStatus);
  tool(tool$invoicesSummary);
  tool(tool$invoicesGet);
  tool(tool$invoicesDelete);
  tool(tool$searchSearch);
  tool(tool$metricsRevenue);
  tool(tool$metricsProfit);
  tool(tool$metricsBurnRate);
  tool(tool$metricsRunway);
  tool(tool$metricsExpenses);
  tool(tool$metricsSpending);
  tool(tool$trackerProjectsList);
  tool(tool$trackerProjectsCreate);
  tool(tool$trackerProjectsUpdate);
  tool(tool$trackerProjectsGet);
  tool(tool$trackerProjectsDelete);
  tool(tool$trackerEntriesList);
  tool(tool$trackerDelete);

  return server;
}
