/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { MiddayCore } from "../core.js";
import { SDKOptions } from "../lib/config.js";
import type { ConsoleLogger } from "./console-logger.js";
import { createRegisterPrompt } from "./prompts.js";
import {
  createRegisterResource,
  createRegisterResourceTemplate,
} from "./resources.js";
import { MCPScope } from "./scopes.js";
import { createRegisterTool } from "./tools.js";
import { tool$bankAccountsCreate } from "./tools/bankAccountsCreate.js";
import { tool$bankAccountsDelete } from "./tools/bankAccountsDelete.js";
import { tool$bankAccountsGet } from "./tools/bankAccountsGet.js";
import { tool$bankAccountsList } from "./tools/bankAccountsList.js";
import { tool$bankAccountsUpdate } from "./tools/bankAccountsUpdate.js";
import { tool$customersCreate } from "./tools/customersCreate.js";
import { tool$customersDelete } from "./tools/customersDelete.js";
import { tool$customersGet } from "./tools/customersGet.js";
import { tool$customersList } from "./tools/customersList.js";
import { tool$customersUpdate } from "./tools/customersUpdate.js";
import { tool$desktopCheckUpdate } from "./tools/desktopCheckUpdate.js";
import { tool$desktopDownloadUpdate } from "./tools/desktopDownloadUpdate.js";
import { tool$documentsDelete } from "./tools/documentsDelete.js";
import { tool$documentsGet } from "./tools/documentsGet.js";
import { tool$documentsGetPreSignedUrl } from "./tools/documentsGetPreSignedUrl.js";
import { tool$documentsList } from "./tools/documentsList.js";
import { tool$filesDownloadFile } from "./tools/filesDownloadFile.js";
import { tool$filesDownloadInvoice } from "./tools/filesDownloadInvoice.js";
import { tool$filesProxy } from "./tools/filesProxy.js";
import { tool$inboxDelete } from "./tools/inboxDelete.js";
import { tool$inboxGet } from "./tools/inboxGet.js";
import { tool$inboxGetPreSignedUrl } from "./tools/inboxGetPreSignedUrl.js";
import { tool$inboxList } from "./tools/inboxList.js";
import { tool$inboxUpdate } from "./tools/inboxUpdate.js";
import { tool$integrationsFortnoxOAuthCallback } from "./tools/integrationsFortnoxOAuthCallback.js";
import { tool$integrationsGetFortnoxInstallUrl } from "./tools/integrationsGetFortnoxInstallUrl.js";
import { tool$integrationsGetGmailInstallUrl } from "./tools/integrationsGetGmailInstallUrl.js";
import { tool$integrationsGetOutlookInstallUrl } from "./tools/integrationsGetOutlookInstallUrl.js";
import { tool$integrationsGetQuickBooksInstallUrl } from "./tools/integrationsGetQuickBooksInstallUrl.js";
import { tool$integrationsGetSlackInstallUrl } from "./tools/integrationsGetSlackInstallUrl.js";
import { tool$integrationsGetXeroInstallUrl } from "./tools/integrationsGetXeroInstallUrl.js";
import { tool$integrationsGmailOAuthCallback } from "./tools/integrationsGmailOAuthCallback.js";
import { tool$integrationsOutlookOAuthCallback } from "./tools/integrationsOutlookOAuthCallback.js";
import { tool$integrationsQuickBooksOAuthCallback } from "./tools/integrationsQuickBooksOAuthCallback.js";
import { tool$integrationsSlackInteractions } from "./tools/integrationsSlackInteractions.js";
import { tool$integrationsSlackOAuthCallback } from "./tools/integrationsSlackOAuthCallback.js";
import { tool$integrationsXeroOAuthCallback } from "./tools/integrationsXeroOAuthCallback.js";
import { tool$invoicePaymentsCreateInvoicePaymentIntent } from "./tools/invoicePaymentsCreateInvoicePaymentIntent.js";
import { tool$invoicePaymentsDisconnectStripe } from "./tools/invoicePaymentsDisconnectStripe.js";
import { tool$invoicePaymentsGetStripeConnectStatus } from "./tools/invoicePaymentsGetStripeConnectStatus.js";
import { tool$invoicePaymentsGetStripeConnectUrl } from "./tools/invoicePaymentsGetStripeConnectUrl.js";
import { tool$invoicePaymentsStripeConnectCallback } from "./tools/invoicePaymentsStripeConnectCallback.js";
import { tool$invoicesCreate } from "./tools/invoicesCreate.js";
import { tool$invoicesDelete } from "./tools/invoicesDelete.js";
import { tool$invoicesGet } from "./tools/invoicesGet.js";
import { tool$invoicesList } from "./tools/invoicesList.js";
import { tool$invoicesPaymentStatus } from "./tools/invoicesPaymentStatus.js";
import { tool$invoicesSummary } from "./tools/invoicesSummary.js";
import { tool$invoicesUpdate } from "./tools/invoicesUpdate.js";
import { tool$notificationsList } from "./tools/notificationsList.js";
import { tool$notificationsUpdateAllStatus } from "./tools/notificationsUpdateAllStatus.js";
import { tool$notificationsUpdateStatus } from "./tools/notificationsUpdateStatus.js";
import { tool$oAuthGetOAuthAuthorization } from "./tools/oAuthGetOAuthAuthorization.js";
import { tool$oAuthPostOAuthAuthorization } from "./tools/oAuthPostOAuthAuthorization.js";
import { tool$oAuthPostOAuthRegister } from "./tools/oAuthPostOAuthRegister.js";
import { tool$oAuthPostOAuthRevoke } from "./tools/oAuthPostOAuthRevoke.js";
import { tool$oAuthPostOAuthToken } from "./tools/oAuthPostOAuthToken.js";
import { tool$reportsBurnRate } from "./tools/reportsBurnRate.js";
import { tool$reportsExpenses } from "./tools/reportsExpenses.js";
import { tool$reportsProfit } from "./tools/reportsProfit.js";
import { tool$reportsRevenue } from "./tools/reportsRevenue.js";
import { tool$reportsRunway } from "./tools/reportsRunway.js";
import { tool$reportsSpending } from "./tools/reportsSpending.js";
import { tool$searchSearch } from "./tools/searchSearch.js";
import { tool$tagsCreate } from "./tools/tagsCreate.js";
import { tool$tagsDelete } from "./tools/tagsDelete.js";
import { tool$tagsGet } from "./tools/tagsGet.js";
import { tool$tagsList } from "./tools/tagsList.js";
import { tool$tagsUpdate } from "./tools/tagsUpdate.js";
import { tool$teamsGet } from "./tools/teamsGet.js";
import { tool$teamsList } from "./tools/teamsList.js";
import { tool$teamsMembers } from "./tools/teamsMembers.js";
import { tool$teamsUpdate } from "./tools/teamsUpdate.js";
import { tool$trackerEntriesCreate } from "./tools/trackerEntriesCreate.js";
import { tool$trackerEntriesCreateBulk } from "./tools/trackerEntriesCreateBulk.js";
import { tool$trackerEntriesDelete } from "./tools/trackerEntriesDelete.js";
import { tool$trackerEntriesList } from "./tools/trackerEntriesList.js";
import { tool$trackerEntriesUpdate } from "./tools/trackerEntriesUpdate.js";
import { tool$trackerProjectsCreate } from "./tools/trackerProjectsCreate.js";
import { tool$trackerProjectsDelete } from "./tools/trackerProjectsDelete.js";
import { tool$trackerProjectsGet } from "./tools/trackerProjectsGet.js";
import { tool$trackerProjectsList } from "./tools/trackerProjectsList.js";
import { tool$trackerProjectsUpdate } from "./tools/trackerProjectsUpdate.js";
import { tool$trackerTimerGetCurrentTimer } from "./tools/trackerTimerGetCurrentTimer.js";
import { tool$trackerTimerGetTimerStatus } from "./tools/trackerTimerGetTimerStatus.js";
import { tool$trackerTimerStartTimer } from "./tools/trackerTimerStartTimer.js";
import { tool$trackerTimerStopTimer } from "./tools/trackerTimerStopTimer.js";
import { tool$transactionsCreate } from "./tools/transactionsCreate.js";
import { tool$transactionsCreateMany } from "./tools/transactionsCreateMany.js";
import { tool$transactionsDelete } from "./tools/transactionsDelete.js";
import { tool$transactionsDeleteMany } from "./tools/transactionsDeleteMany.js";
import { tool$transactionsGet } from "./tools/transactionsGet.js";
import { tool$transactionsGetAttachmentPreSignedUrl } from "./tools/transactionsGetAttachmentPreSignedUrl.js";
import { tool$transactionsList } from "./tools/transactionsList.js";
import { tool$transactionsUpdate } from "./tools/transactionsUpdate.js";
import { tool$transactionsUpdateMany } from "./tools/transactionsUpdateMany.js";
import { tool$usersGet } from "./tools/usersGet.js";
import { tool$usersUpdate } from "./tools/usersUpdate.js";
import { tool$webhooksInboxWebhook } from "./tools/webhooksInboxWebhook.js";
import { tool$webhooksPlaidWebhook } from "./tools/webhooksPlaidWebhook.js";
import { tool$webhooksPolarWebhook } from "./tools/webhooksPolarWebhook.js";
import { tool$webhooksStripeWebhook } from "./tools/webhooksStripeWebhook.js";
import { tool$webhooksTellerWebhook } from "./tools/webhooksTellerWebhook.js";

export function createMCPServer(deps: {
  logger: ConsoleLogger;
  allowedTools?: string[] | undefined;
  scopes?: MCPScope[] | undefined;
  serverURL?: string | undefined;
  security?: SDKOptions["security"] | undefined;
  serverIdx?: SDKOptions["serverIdx"] | undefined;
}) {
  const server = new McpServer({
    name: "Midday",
    version: "0.6.1",
  });

  const client = new MiddayCore({
    security: deps.security,
    serverURL: deps.serverURL,
    serverIdx: deps.serverIdx,
  });

  const scopes = new Set(deps.scopes);

  const allowedTools = deps.allowedTools && new Set(deps.allowedTools);
  const tool = createRegisterTool(
    deps.logger,
    server,
    client,
    scopes,
    allowedTools,
  );
  const resource = createRegisterResource(deps.logger, server, client, scopes);
  const resourceTemplate = createRegisterResourceTemplate(
    deps.logger,
    server,
    client,
    scopes,
  );
  const prompt = createRegisterPrompt(deps.logger, server, client, scopes);
  const register = { tool, resource, resourceTemplate, prompt };
  void register; // suppress unused warnings

  tool(tool$oAuthPostOAuthRegister);
  tool(tool$oAuthGetOAuthAuthorization);
  tool(tool$oAuthPostOAuthAuthorization);
  tool(tool$oAuthPostOAuthToken);
  tool(tool$oAuthPostOAuthRevoke);
  tool(tool$webhooksInboxWebhook);
  tool(tool$webhooksPlaidWebhook);
  tool(tool$webhooksPolarWebhook);
  tool(tool$webhooksStripeWebhook);
  tool(tool$webhooksTellerWebhook);
  tool(tool$filesProxy);
  tool(tool$filesDownloadFile);
  tool(tool$filesDownloadInvoice);
  tool(tool$integrationsSlackOAuthCallback);
  tool(tool$integrationsGetSlackInstallUrl);
  tool(tool$integrationsSlackInteractions);
  tool(tool$integrationsGmailOAuthCallback);
  tool(tool$integrationsGetGmailInstallUrl);
  tool(tool$integrationsOutlookOAuthCallback);
  tool(tool$integrationsGetOutlookInstallUrl);
  tool(tool$integrationsXeroOAuthCallback);
  tool(tool$integrationsGetXeroInstallUrl);
  tool(tool$integrationsQuickBooksOAuthCallback);
  tool(tool$integrationsGetQuickBooksInstallUrl);
  tool(tool$integrationsFortnoxOAuthCallback);
  tool(tool$integrationsGetFortnoxInstallUrl);
  tool(tool$invoicePaymentsGetStripeConnectUrl);
  tool(tool$invoicePaymentsStripeConnectCallback);
  tool(tool$invoicePaymentsDisconnectStripe);
  tool(tool$invoicePaymentsCreateInvoicePaymentIntent);
  tool(tool$invoicePaymentsGetStripeConnectStatus);
  tool(tool$desktopCheckUpdate);
  tool(tool$desktopDownloadUpdate);
  tool(tool$notificationsList);
  tool(tool$notificationsUpdateStatus);
  tool(tool$notificationsUpdateAllStatus);
  tool(tool$transactionsList);
  tool(tool$transactionsCreate);
  tool(tool$transactionsGet);
  tool(tool$transactionsUpdate);
  tool(tool$transactionsDelete);
  tool(tool$transactionsGetAttachmentPreSignedUrl);
  tool(tool$transactionsUpdateMany);
  tool(tool$transactionsCreateMany);
  tool(tool$transactionsDeleteMany);
  tool(tool$teamsList);
  tool(tool$teamsGet);
  tool(tool$teamsUpdate);
  tool(tool$teamsMembers);
  tool(tool$usersGet);
  tool(tool$usersUpdate);
  tool(tool$customersList);
  tool(tool$customersCreate);
  tool(tool$customersGet);
  tool(tool$customersUpdate);
  tool(tool$customersDelete);
  tool(tool$bankAccountsList);
  tool(tool$bankAccountsCreate);
  tool(tool$bankAccountsGet);
  tool(tool$bankAccountsUpdate);
  tool(tool$bankAccountsDelete);
  tool(tool$tagsList);
  tool(tool$tagsCreate);
  tool(tool$tagsGet);
  tool(tool$tagsUpdate);
  tool(tool$tagsDelete);
  tool(tool$documentsList);
  tool(tool$documentsGet);
  tool(tool$documentsDelete);
  tool(tool$documentsGetPreSignedUrl);
  tool(tool$inboxList);
  tool(tool$inboxGet);
  tool(tool$inboxDelete);
  tool(tool$inboxUpdate);
  tool(tool$inboxGetPreSignedUrl);
  tool(tool$invoicesList);
  tool(tool$invoicesCreate);
  tool(tool$invoicesPaymentStatus);
  tool(tool$invoicesSummary);
  tool(tool$invoicesGet);
  tool(tool$invoicesUpdate);
  tool(tool$invoicesDelete);
  tool(tool$searchSearch);
  tool(tool$reportsRevenue);
  tool(tool$reportsProfit);
  tool(tool$reportsBurnRate);
  tool(tool$reportsRunway);
  tool(tool$reportsExpenses);
  tool(tool$reportsSpending);
  tool(tool$trackerProjectsList);
  tool(tool$trackerProjectsCreate);
  tool(tool$trackerProjectsUpdate);
  tool(tool$trackerProjectsGet);
  tool(tool$trackerProjectsDelete);
  tool(tool$trackerEntriesList);
  tool(tool$trackerEntriesCreate);
  tool(tool$trackerEntriesCreateBulk);
  tool(tool$trackerEntriesUpdate);
  tool(tool$trackerEntriesDelete);
  tool(tool$trackerTimerStartTimer);
  tool(tool$trackerTimerStopTimer);
  tool(tool$trackerTimerGetCurrentTimer);
  tool(tool$trackerTimerGetTimerStatus);

  return server;
}
