/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { desktopCheckUpdate } from "../funcs/desktopCheckUpdate.js";
import { desktopDownloadUpdate } from "../funcs/desktopDownloadUpdate.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Desktop extends ClientSDK {
  /**
   * Check for desktop app updates
   *
   * @remarks
   * Returns the latest desktop app version info in Tauri updater format. Download URLs are rewritten to proxy through this API.
   */
  async checkUpdate(
    options?: RequestOptions,
  ): Promise<operations.CheckDesktopUpdateResponse> {
    return unwrapAsync(desktopCheckUpdate(
      this,
      options,
    ));
  }

  /**
   * Download desktop app update artifact
   *
   * @remarks
   * Proxies the download of a desktop app update artifact from GitHub releases. Only URLs pointing to the midday-ai/midday repository are accepted.
   */
  async downloadUpdate(
    request: operations.DownloadDesktopUpdateRequest,
    options?: RequestOptions,
  ): Promise<ReadableStream<Uint8Array>> {
    return unwrapAsync(desktopDownloadUpdate(
      this,
      request,
      options,
    ));
  }
}
