/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { searchSearch } from "../funcs/searchSearch.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Search extends ClientSDK {
  /**
   * Search
   *
   * @remarks
   * Search across all data, invoices, documents, customers, transactions, and more.
   */
  async search(
    request: operations.SearchRequest,
    options?: RequestOptions,
  ): Promise<Array<operations.SearchResponse>> {
    return unwrapAsync(searchSearch(
      this,
      request,
      options,
    ));
  }
}
