/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

/**
 * Example usage of the @midday-ai/sdk SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx transactionsList.ts
 */

import { Midday } from "@midday-ai/sdk";

const midday = new Midday({
  token: "MIDDAY_API_KEY",
});

async function main() {
  const result = await midday.list({
    cursor: "eyJpZCI6IjEyMyJ9",
    sort: [
      "date",
      "desc",
    ],
    pageSize: 50,
    q: "office supplies",
    categories: [
      "office-supplies",
      "travel",
    ],
    tags: [
      "tag-1",
      "tag-2",
    ],
    start: "2024-04-01T00:00:00.000Z",
    end: "2024-04-30T23:59:59.999Z",
    accounts: [
      "account-1",
      "account-2",
    ],
    assignees: [
      "user-1",
      "user-2",
    ],
    statuses: [
      "pending",
      "completed",
    ],
    recurring: [
      "monthly",
      "annually",
    ],
    attachments: "include",
    amountRange: [
      100,
      1000,
    ],
    amount: [
      "150.75",
      "299.99",
    ],
    type: "expense",
  });

  console.log(result);
}

main().catch(console.error);
