workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Midday API:
        inputs:
            - location: https://api.midday.ai/openapi
        registry:
            location: registry.speakeasyapi.dev/midday/midday/midday-api
targets:
    midday:
        target: typescript
        source: Midday API
        codeSamples:
            registry:
                location: registry.speakeasyapi.dev/midday/midday/midday-api-typescript-code-samples
            labelOverride:
                fixedValue: Typescript (SDK)
            blocking: false
