/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type DeleteInboxItemRequest = {
  /**
   * The unique identifier of the inbox item to delete.
   */
  id: string;
};

/**
 * Response schema for a successfully deleted inbox item.
 */
export type DeleteInboxItemResponseBody = {
  /**
   * The unique identifier of the deleted inbox item.
   */
  id: string;
};

export type DeleteInboxItemResponse =
  | DeleteInboxItemResponseBody
  | models.ErrorResponse;

/** @internal */
export const DeleteInboxItemRequest$inboundSchema: z.ZodType<
  DeleteInboxItemRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
});

/** @internal */
export type DeleteInboxItemRequest$Outbound = {
  id: string;
};

/** @internal */
export const DeleteInboxItemRequest$outboundSchema: z.ZodType<
  DeleteInboxItemRequest$Outbound,
  z.ZodTypeDef,
  DeleteInboxItemRequest
> = z.object({
  id: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteInboxItemRequest$ {
  /** @deprecated use `DeleteInboxItemRequest$inboundSchema` instead. */
  export const inboundSchema = DeleteInboxItemRequest$inboundSchema;
  /** @deprecated use `DeleteInboxItemRequest$outboundSchema` instead. */
  export const outboundSchema = DeleteInboxItemRequest$outboundSchema;
  /** @deprecated use `DeleteInboxItemRequest$Outbound` instead. */
  export type Outbound = DeleteInboxItemRequest$Outbound;
}

export function deleteInboxItemRequestToJSON(
  deleteInboxItemRequest: DeleteInboxItemRequest,
): string {
  return JSON.stringify(
    DeleteInboxItemRequest$outboundSchema.parse(deleteInboxItemRequest),
  );
}

export function deleteInboxItemRequestFromJSON(
  jsonString: string,
): SafeParseResult<DeleteInboxItemRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteInboxItemRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteInboxItemRequest' from JSON`,
  );
}

/** @internal */
export const DeleteInboxItemResponseBody$inboundSchema: z.ZodType<
  DeleteInboxItemResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
});

/** @internal */
export type DeleteInboxItemResponseBody$Outbound = {
  id: string;
};

/** @internal */
export const DeleteInboxItemResponseBody$outboundSchema: z.ZodType<
  DeleteInboxItemResponseBody$Outbound,
  z.ZodTypeDef,
  DeleteInboxItemResponseBody
> = z.object({
  id: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteInboxItemResponseBody$ {
  /** @deprecated use `DeleteInboxItemResponseBody$inboundSchema` instead. */
  export const inboundSchema = DeleteInboxItemResponseBody$inboundSchema;
  /** @deprecated use `DeleteInboxItemResponseBody$outboundSchema` instead. */
  export const outboundSchema = DeleteInboxItemResponseBody$outboundSchema;
  /** @deprecated use `DeleteInboxItemResponseBody$Outbound` instead. */
  export type Outbound = DeleteInboxItemResponseBody$Outbound;
}

export function deleteInboxItemResponseBodyToJSON(
  deleteInboxItemResponseBody: DeleteInboxItemResponseBody,
): string {
  return JSON.stringify(
    DeleteInboxItemResponseBody$outboundSchema.parse(
      deleteInboxItemResponseBody,
    ),
  );
}

export function deleteInboxItemResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<DeleteInboxItemResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteInboxItemResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteInboxItemResponseBody' from JSON`,
  );
}

/** @internal */
export const DeleteInboxItemResponse$inboundSchema: z.ZodType<
  DeleteInboxItemResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => DeleteInboxItemResponseBody$inboundSchema),
  models.ErrorResponse$inboundSchema,
]);

/** @internal */
export type DeleteInboxItemResponse$Outbound =
  | DeleteInboxItemResponseBody$Outbound
  | models.ErrorResponse$Outbound;

/** @internal */
export const DeleteInboxItemResponse$outboundSchema: z.ZodType<
  DeleteInboxItemResponse$Outbound,
  z.ZodTypeDef,
  DeleteInboxItemResponse
> = z.union([
  z.lazy(() => DeleteInboxItemResponseBody$outboundSchema),
  models.ErrorResponse$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteInboxItemResponse$ {
  /** @deprecated use `DeleteInboxItemResponse$inboundSchema` instead. */
  export const inboundSchema = DeleteInboxItemResponse$inboundSchema;
  /** @deprecated use `DeleteInboxItemResponse$outboundSchema` instead. */
  export const outboundSchema = DeleteInboxItemResponse$outboundSchema;
  /** @deprecated use `DeleteInboxItemResponse$Outbound` instead. */
  export type Outbound = DeleteInboxItemResponse$Outbound;
}

export function deleteInboxItemResponseToJSON(
  deleteInboxItemResponse: DeleteInboxItemResponse,
): string {
  return JSON.stringify(
    DeleteInboxItemResponse$outboundSchema.parse(deleteInboxItemResponse),
  );
}

export function deleteInboxItemResponseFromJSON(
  jsonString: string,
): SafeParseResult<DeleteInboxItemResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteInboxItemResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteInboxItemResponse' from JSON`,
  );
}
