/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DeleteTagRequest = {
  /**
   * The UUID of the tag to delete.
   */
  id: string;
};

/** @internal */
export const DeleteTagRequest$inboundSchema: z.ZodType<
  DeleteTagRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
});
/** @internal */
export type DeleteTagRequest$Outbound = {
  id: string;
};

/** @internal */
export const DeleteTagRequest$outboundSchema: z.ZodType<
  DeleteTagRequest$Outbound,
  z.ZodTypeDef,
  DeleteTagRequest
> = z.object({
  id: z.string(),
});

export function deleteTagRequestToJSON(
  deleteTagRequest: DeleteTagRequest,
): string {
  return JSON.stringify(
    DeleteTagRequest$outboundSchema.parse(deleteTagRequest),
  );
}
export function deleteTagRequestFromJSON(
  jsonString: string,
): SafeParseResult<DeleteTagRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteTagRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteTagRequest' from JSON`,
  );
}
