/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type DeleteDocumentRequest = {
  id: string;
};

/**
 * Document deleted successfully
 */
export type DeleteDocumentResponseBody = {
  id: string;
};

export type DeleteDocumentResponse =
  | DeleteDocumentResponseBody
  | models.ErrorResponse;

/** @internal */
export const DeleteDocumentRequest$inboundSchema: z.ZodType<
  DeleteDocumentRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
});

/** @internal */
export type DeleteDocumentRequest$Outbound = {
  id: string;
};

/** @internal */
export const DeleteDocumentRequest$outboundSchema: z.ZodType<
  DeleteDocumentRequest$Outbound,
  z.ZodTypeDef,
  DeleteDocumentRequest
> = z.object({
  id: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteDocumentRequest$ {
  /** @deprecated use `DeleteDocumentRequest$inboundSchema` instead. */
  export const inboundSchema = DeleteDocumentRequest$inboundSchema;
  /** @deprecated use `DeleteDocumentRequest$outboundSchema` instead. */
  export const outboundSchema = DeleteDocumentRequest$outboundSchema;
  /** @deprecated use `DeleteDocumentRequest$Outbound` instead. */
  export type Outbound = DeleteDocumentRequest$Outbound;
}

export function deleteDocumentRequestToJSON(
  deleteDocumentRequest: DeleteDocumentRequest,
): string {
  return JSON.stringify(
    DeleteDocumentRequest$outboundSchema.parse(deleteDocumentRequest),
  );
}

export function deleteDocumentRequestFromJSON(
  jsonString: string,
): SafeParseResult<DeleteDocumentRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteDocumentRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteDocumentRequest' from JSON`,
  );
}

/** @internal */
export const DeleteDocumentResponseBody$inboundSchema: z.ZodType<
  DeleteDocumentResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
});

/** @internal */
export type DeleteDocumentResponseBody$Outbound = {
  id: string;
};

/** @internal */
export const DeleteDocumentResponseBody$outboundSchema: z.ZodType<
  DeleteDocumentResponseBody$Outbound,
  z.ZodTypeDef,
  DeleteDocumentResponseBody
> = z.object({
  id: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteDocumentResponseBody$ {
  /** @deprecated use `DeleteDocumentResponseBody$inboundSchema` instead. */
  export const inboundSchema = DeleteDocumentResponseBody$inboundSchema;
  /** @deprecated use `DeleteDocumentResponseBody$outboundSchema` instead. */
  export const outboundSchema = DeleteDocumentResponseBody$outboundSchema;
  /** @deprecated use `DeleteDocumentResponseBody$Outbound` instead. */
  export type Outbound = DeleteDocumentResponseBody$Outbound;
}

export function deleteDocumentResponseBodyToJSON(
  deleteDocumentResponseBody: DeleteDocumentResponseBody,
): string {
  return JSON.stringify(
    DeleteDocumentResponseBody$outboundSchema.parse(deleteDocumentResponseBody),
  );
}

export function deleteDocumentResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<DeleteDocumentResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteDocumentResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteDocumentResponseBody' from JSON`,
  );
}

/** @internal */
export const DeleteDocumentResponse$inboundSchema: z.ZodType<
  DeleteDocumentResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => DeleteDocumentResponseBody$inboundSchema),
  models.ErrorResponse$inboundSchema,
]);

/** @internal */
export type DeleteDocumentResponse$Outbound =
  | DeleteDocumentResponseBody$Outbound
  | models.ErrorResponse$Outbound;

/** @internal */
export const DeleteDocumentResponse$outboundSchema: z.ZodType<
  DeleteDocumentResponse$Outbound,
  z.ZodTypeDef,
  DeleteDocumentResponse
> = z.union([
  z.lazy(() => DeleteDocumentResponseBody$outboundSchema),
  models.ErrorResponse$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace DeleteDocumentResponse$ {
  /** @deprecated use `DeleteDocumentResponse$inboundSchema` instead. */
  export const inboundSchema = DeleteDocumentResponse$inboundSchema;
  /** @deprecated use `DeleteDocumentResponse$outboundSchema` instead. */
  export const outboundSchema = DeleteDocumentResponse$outboundSchema;
  /** @deprecated use `DeleteDocumentResponse$Outbound` instead. */
  export type Outbound = DeleteDocumentResponse$Outbound;
}

export function deleteDocumentResponseToJSON(
  deleteDocumentResponse: DeleteDocumentResponse,
): string {
  return JSON.stringify(
    DeleteDocumentResponse$outboundSchema.parse(deleteDocumentResponse),
  );
}

export function deleteDocumentResponseFromJSON(
  jsonString: string,
): SafeParseResult<DeleteDocumentResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DeleteDocumentResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DeleteDocumentResponse' from JSON`,
  );
}
