/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type DownloadInvoiceRequest = {
  /**
   * Invoice ID (UUID). Requires team file key (fk) query parameter for authentication.
   */
  id?: string | undefined;
  /**
   * Team file key for authenticated invoice access. Required when using invoice ID. This key is returned in the user data response (GET /users/me) as the `fileKey` field.
   */
  fk?: string | undefined;
  /**
   * Invoice access token for public access. When used alone (without id), allows public access to the invoice.
   */
  token?: string | undefined;
  /**
   * If true, the PDF will be displayed inline. If false, it will be downloaded.
   */
  preview?: boolean | null | undefined;
};

/** @internal */
export const DownloadInvoiceRequest$inboundSchema: z.ZodType<
  DownloadInvoiceRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string().optional(),
  fk: z.string().optional(),
  token: z.string().optional(),
  preview: z.nullable(z.boolean().default(false)),
});
/** @internal */
export type DownloadInvoiceRequest$Outbound = {
  id?: string | undefined;
  fk?: string | undefined;
  token?: string | undefined;
  preview: boolean | null;
};

/** @internal */
export const DownloadInvoiceRequest$outboundSchema: z.ZodType<
  DownloadInvoiceRequest$Outbound,
  z.ZodTypeDef,
  DownloadInvoiceRequest
> = z.object({
  id: z.string().optional(),
  fk: z.string().optional(),
  token: z.string().optional(),
  preview: z.nullable(z.boolean().default(false)),
});

export function downloadInvoiceRequestToJSON(
  downloadInvoiceRequest: DownloadInvoiceRequest,
): string {
  return JSON.stringify(
    DownloadInvoiceRequest$outboundSchema.parse(downloadInvoiceRequest),
  );
}
export function downloadInvoiceRequestFromJSON(
  jsonString: string,
): SafeParseResult<DownloadInvoiceRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => DownloadInvoiceRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'DownloadInvoiceRequest' from JSON`,
  );
}
