/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Gmail install URL
 */
export type GetGmailInstallUrlResponse = {
  url: string;
};

/** @internal */
export const GetGmailInstallUrlResponse$inboundSchema: z.ZodType<
  GetGmailInstallUrlResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  url: z.string(),
});
/** @internal */
export type GetGmailInstallUrlResponse$Outbound = {
  url: string;
};

/** @internal */
export const GetGmailInstallUrlResponse$outboundSchema: z.ZodType<
  GetGmailInstallUrlResponse$Outbound,
  z.ZodTypeDef,
  GetGmailInstallUrlResponse
> = z.object({
  url: z.string(),
});

export function getGmailInstallUrlResponseToJSON(
  getGmailInstallUrlResponse: GetGmailInstallUrlResponse,
): string {
  return JSON.stringify(
    GetGmailInstallUrlResponse$outboundSchema.parse(getGmailInstallUrlResponse),
  );
}
export function getGmailInstallUrlResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetGmailInstallUrlResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetGmailInstallUrlResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetGmailInstallUrlResponse' from JSON`,
  );
}
