/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

/**
 * Payment status for the authenticated team.
 */
export type GetInvoicePaymentStatusResponseBody = {
  /**
   * Score associated with the invoice payment status
   */
  score: number;
  /**
   * The payment status of the invoice
   */
  paymentStatus: string;
};

export type GetInvoicePaymentStatusResponse =
  | GetInvoicePaymentStatusResponseBody
  | models.ErrorResponse;

/** @internal */
export const GetInvoicePaymentStatusResponseBody$inboundSchema: z.ZodType<
  GetInvoicePaymentStatusResponseBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  score: z.number(),
  paymentStatus: z.string(),
});

/** @internal */
export type GetInvoicePaymentStatusResponseBody$Outbound = {
  score: number;
  paymentStatus: string;
};

/** @internal */
export const GetInvoicePaymentStatusResponseBody$outboundSchema: z.ZodType<
  GetInvoicePaymentStatusResponseBody$Outbound,
  z.ZodTypeDef,
  GetInvoicePaymentStatusResponseBody
> = z.object({
  score: z.number(),
  paymentStatus: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetInvoicePaymentStatusResponseBody$ {
  /** @deprecated use `GetInvoicePaymentStatusResponseBody$inboundSchema` instead. */
  export const inboundSchema =
    GetInvoicePaymentStatusResponseBody$inboundSchema;
  /** @deprecated use `GetInvoicePaymentStatusResponseBody$outboundSchema` instead. */
  export const outboundSchema =
    GetInvoicePaymentStatusResponseBody$outboundSchema;
  /** @deprecated use `GetInvoicePaymentStatusResponseBody$Outbound` instead. */
  export type Outbound = GetInvoicePaymentStatusResponseBody$Outbound;
}

export function getInvoicePaymentStatusResponseBodyToJSON(
  getInvoicePaymentStatusResponseBody: GetInvoicePaymentStatusResponseBody,
): string {
  return JSON.stringify(
    GetInvoicePaymentStatusResponseBody$outboundSchema.parse(
      getInvoicePaymentStatusResponseBody,
    ),
  );
}

export function getInvoicePaymentStatusResponseBodyFromJSON(
  jsonString: string,
): SafeParseResult<GetInvoicePaymentStatusResponseBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) =>
      GetInvoicePaymentStatusResponseBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetInvoicePaymentStatusResponseBody' from JSON`,
  );
}

/** @internal */
export const GetInvoicePaymentStatusResponse$inboundSchema: z.ZodType<
  GetInvoicePaymentStatusResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  z.lazy(() => GetInvoicePaymentStatusResponseBody$inboundSchema),
  models.ErrorResponse$inboundSchema,
]);

/** @internal */
export type GetInvoicePaymentStatusResponse$Outbound =
  | GetInvoicePaymentStatusResponseBody$Outbound
  | models.ErrorResponse$Outbound;

/** @internal */
export const GetInvoicePaymentStatusResponse$outboundSchema: z.ZodType<
  GetInvoicePaymentStatusResponse$Outbound,
  z.ZodTypeDef,
  GetInvoicePaymentStatusResponse
> = z.union([
  z.lazy(() => GetInvoicePaymentStatusResponseBody$outboundSchema),
  models.ErrorResponse$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetInvoicePaymentStatusResponse$ {
  /** @deprecated use `GetInvoicePaymentStatusResponse$inboundSchema` instead. */
  export const inboundSchema = GetInvoicePaymentStatusResponse$inboundSchema;
  /** @deprecated use `GetInvoicePaymentStatusResponse$outboundSchema` instead. */
  export const outboundSchema = GetInvoicePaymentStatusResponse$outboundSchema;
  /** @deprecated use `GetInvoicePaymentStatusResponse$Outbound` instead. */
  export type Outbound = GetInvoicePaymentStatusResponse$Outbound;
}

export function getInvoicePaymentStatusResponseToJSON(
  getInvoicePaymentStatusResponse: GetInvoicePaymentStatusResponse,
): string {
  return JSON.stringify(
    GetInvoicePaymentStatusResponse$outboundSchema.parse(
      getInvoicePaymentStatusResponse,
    ),
  );
}

export function getInvoicePaymentStatusResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetInvoicePaymentStatusResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetInvoicePaymentStatusResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetInvoicePaymentStatusResponse' from JSON`,
  );
}
