/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetProfitMetricsRequest = {
  from: string;
  to: string;
  currency?: string | undefined;
};

/** @internal */
export const GetProfitMetricsRequest$inboundSchema: z.ZodType<
  GetProfitMetricsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  from: z.string(),
  to: z.string(),
  currency: z.string().optional(),
});

/** @internal */
export type GetProfitMetricsRequest$Outbound = {
  from: string;
  to: string;
  currency?: string | undefined;
};

/** @internal */
export const GetProfitMetricsRequest$outboundSchema: z.ZodType<
  GetProfitMetricsRequest$Outbound,
  z.ZodTypeDef,
  GetProfitMetricsRequest
> = z.object({
  from: z.string(),
  to: z.string(),
  currency: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetProfitMetricsRequest$ {
  /** @deprecated use `GetProfitMetricsRequest$inboundSchema` instead. */
  export const inboundSchema = GetProfitMetricsRequest$inboundSchema;
  /** @deprecated use `GetProfitMetricsRequest$outboundSchema` instead. */
  export const outboundSchema = GetProfitMetricsRequest$outboundSchema;
  /** @deprecated use `GetProfitMetricsRequest$Outbound` instead. */
  export type Outbound = GetProfitMetricsRequest$Outbound;
}

export function getProfitMetricsRequestToJSON(
  getProfitMetricsRequest: GetProfitMetricsRequest,
): string {
  return JSON.stringify(
    GetProfitMetricsRequest$outboundSchema.parse(getProfitMetricsRequest),
  );
}

export function getProfitMetricsRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetProfitMetricsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetProfitMetricsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetProfitMetricsRequest' from JSON`,
  );
}
