/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetRunwayReportsRequest = {
  from: string;
  to: string;
  currency?: string | undefined;
};

/** @internal */
export const GetRunwayReportsRequest$inboundSchema: z.ZodType<
  GetRunwayReportsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  from: z.string(),
  to: z.string(),
  currency: z.string().optional(),
});

/** @internal */
export type GetRunwayReportsRequest$Outbound = {
  from: string;
  to: string;
  currency?: string | undefined;
};

/** @internal */
export const GetRunwayReportsRequest$outboundSchema: z.ZodType<
  GetRunwayReportsRequest$Outbound,
  z.ZodTypeDef,
  GetRunwayReportsRequest
> = z.object({
  from: z.string(),
  to: z.string(),
  currency: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetRunwayReportsRequest$ {
  /** @deprecated use `GetRunwayReportsRequest$inboundSchema` instead. */
  export const inboundSchema = GetRunwayReportsRequest$inboundSchema;
  /** @deprecated use `GetRunwayReportsRequest$outboundSchema` instead. */
  export const outboundSchema = GetRunwayReportsRequest$outboundSchema;
  /** @deprecated use `GetRunwayReportsRequest$Outbound` instead. */
  export type Outbound = GetRunwayReportsRequest$Outbound;
}

export function getRunwayReportsRequestToJSON(
  getRunwayReportsRequest: GetRunwayReportsRequest,
): string {
  return JSON.stringify(
    GetRunwayReportsRequest$outboundSchema.parse(getRunwayReportsRequest),
  );
}

export function getRunwayReportsRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetRunwayReportsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetRunwayReportsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetRunwayReportsRequest' from JSON`,
  );
}
