/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Stripe Connect status
 */
export type GetStripeConnectStatusResponse = {
  connected: boolean;
  status: string | null;
  stripeAccountId: string | null;
};

/** @internal */
export const GetStripeConnectStatusResponse$inboundSchema: z.ZodType<
  GetStripeConnectStatusResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  connected: z.boolean(),
  status: z.nullable(z.string()),
  stripeAccountId: z.nullable(z.string()),
});

/** @internal */
export type GetStripeConnectStatusResponse$Outbound = {
  connected: boolean;
  status: string | null;
  stripeAccountId: string | null;
};

/** @internal */
export const GetStripeConnectStatusResponse$outboundSchema: z.ZodType<
  GetStripeConnectStatusResponse$Outbound,
  z.ZodTypeDef,
  GetStripeConnectStatusResponse
> = z.object({
  connected: z.boolean(),
  status: z.nullable(z.string()),
  stripeAccountId: z.nullable(z.string()),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetStripeConnectStatusResponse$ {
  /** @deprecated use `GetStripeConnectStatusResponse$inboundSchema` instead. */
  export const inboundSchema = GetStripeConnectStatusResponse$inboundSchema;
  /** @deprecated use `GetStripeConnectStatusResponse$outboundSchema` instead. */
  export const outboundSchema = GetStripeConnectStatusResponse$outboundSchema;
  /** @deprecated use `GetStripeConnectStatusResponse$Outbound` instead. */
  export type Outbound = GetStripeConnectStatusResponse$Outbound;
}

export function getStripeConnectStatusResponseToJSON(
  getStripeConnectStatusResponse: GetStripeConnectStatusResponse,
): string {
  return JSON.stringify(
    GetStripeConnectStatusResponse$outboundSchema.parse(
      getStripeConnectStatusResponse,
    ),
  );
}

export function getStripeConnectStatusResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetStripeConnectStatusResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetStripeConnectStatusResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetStripeConnectStatusResponse' from JSON`,
  );
}
