/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetSpendingReportsRequest = {
  /**
   * Start date (ISO 8601 format)
   */
  from: string;
  /**
   * End date (ISO 8601 format)
   */
  to: string;
  /**
   * Currency code (ISO 4217)
   */
  currency?: string | undefined;
};

/** @internal */
export const GetSpendingReportsRequest$inboundSchema: z.ZodType<
  GetSpendingReportsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  from: z.string(),
  to: z.string(),
  currency: z.string().optional(),
});
/** @internal */
export type GetSpendingReportsRequest$Outbound = {
  from: string;
  to: string;
  currency?: string | undefined;
};

/** @internal */
export const GetSpendingReportsRequest$outboundSchema: z.ZodType<
  GetSpendingReportsRequest$Outbound,
  z.ZodTypeDef,
  GetSpendingReportsRequest
> = z.object({
  from: z.string(),
  to: z.string(),
  currency: z.string().optional(),
});

export function getSpendingReportsRequestToJSON(
  getSpendingReportsRequest: GetSpendingReportsRequest,
): string {
  return JSON.stringify(
    GetSpendingReportsRequest$outboundSchema.parse(getSpendingReportsRequest),
  );
}
export function getSpendingReportsRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetSpendingReportsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetSpendingReportsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetSpendingReportsRequest' from JSON`,
  );
}
