/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Slack install URL
 */
export type GetSlackInstallUrlResponse = {
  url: string;
};

/** @internal */
export const GetSlackInstallUrlResponse$inboundSchema: z.ZodType<
  GetSlackInstallUrlResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  url: z.string(),
});

/** @internal */
export type GetSlackInstallUrlResponse$Outbound = {
  url: string;
};

/** @internal */
export const GetSlackInstallUrlResponse$outboundSchema: z.ZodType<
  GetSlackInstallUrlResponse$Outbound,
  z.ZodTypeDef,
  GetSlackInstallUrlResponse
> = z.object({
  url: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetSlackInstallUrlResponse$ {
  /** @deprecated use `GetSlackInstallUrlResponse$inboundSchema` instead. */
  export const inboundSchema = GetSlackInstallUrlResponse$inboundSchema;
  /** @deprecated use `GetSlackInstallUrlResponse$outboundSchema` instead. */
  export const outboundSchema = GetSlackInstallUrlResponse$outboundSchema;
  /** @deprecated use `GetSlackInstallUrlResponse$Outbound` instead. */
  export type Outbound = GetSlackInstallUrlResponse$Outbound;
}

export function getSlackInstallUrlResponseToJSON(
  getSlackInstallUrlResponse: GetSlackInstallUrlResponse,
): string {
  return JSON.stringify(
    GetSlackInstallUrlResponse$outboundSchema.parse(getSlackInstallUrlResponse),
  );
}

export function getSlackInstallUrlResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetSlackInstallUrlResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetSlackInstallUrlResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetSlackInstallUrlResponse' from JSON`,
  );
}
