/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetV1SearchRequest = {
  searchTerm?: string | undefined;
  language?: string | undefined;
  limit?: number | undefined;
  itemsPerTableLimit?: number | undefined;
  relevanceThreshold?: number | undefined;
};

export type GetV1SearchResponse = {
  /**
   * Unique identifier for the search result item.
   */
  id: string;
  /**
   * Type of the entity returned (e.g., invoice, customer, transaction).
   */
  type: string;
  /**
   * Relevance score for the search result.
   */
  relevance: number;
  /**
   * ISO 8601 timestamp when the entity was created.
   */
  createdAt: string;
  /**
   * Additional data for the search result, structure depends on the type.
   */
  data?: any | null | undefined;
};

/** @internal */
export const GetV1SearchRequest$inboundSchema: z.ZodType<
  GetV1SearchRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  searchTerm: z.string().optional(),
  language: z.string().optional(),
  limit: z.number().default(30),
  itemsPerTableLimit: z.number().default(5),
  relevanceThreshold: z.number().default(0.01),
});

/** @internal */
export type GetV1SearchRequest$Outbound = {
  searchTerm?: string | undefined;
  language?: string | undefined;
  limit: number;
  itemsPerTableLimit: number;
  relevanceThreshold: number;
};

/** @internal */
export const GetV1SearchRequest$outboundSchema: z.ZodType<
  GetV1SearchRequest$Outbound,
  z.ZodTypeDef,
  GetV1SearchRequest
> = z.object({
  searchTerm: z.string().optional(),
  language: z.string().optional(),
  limit: z.number().default(30),
  itemsPerTableLimit: z.number().default(5),
  relevanceThreshold: z.number().default(0.01),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetV1SearchRequest$ {
  /** @deprecated use `GetV1SearchRequest$inboundSchema` instead. */
  export const inboundSchema = GetV1SearchRequest$inboundSchema;
  /** @deprecated use `GetV1SearchRequest$outboundSchema` instead. */
  export const outboundSchema = GetV1SearchRequest$outboundSchema;
  /** @deprecated use `GetV1SearchRequest$Outbound` instead. */
  export type Outbound = GetV1SearchRequest$Outbound;
}

export function getV1SearchRequestToJSON(
  getV1SearchRequest: GetV1SearchRequest,
): string {
  return JSON.stringify(
    GetV1SearchRequest$outboundSchema.parse(getV1SearchRequest),
  );
}

export function getV1SearchRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetV1SearchRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1SearchRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1SearchRequest' from JSON`,
  );
}

/** @internal */
export const GetV1SearchResponse$inboundSchema: z.ZodType<
  GetV1SearchResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  type: z.string(),
  relevance: z.number(),
  created_at: z.string(),
  data: z.nullable(z.any()).optional(),
}).transform((v) => {
  return remap$(v, {
    "created_at": "createdAt",
  });
});

/** @internal */
export type GetV1SearchResponse$Outbound = {
  id: string;
  type: string;
  relevance: number;
  created_at: string;
  data?: any | null | undefined;
};

/** @internal */
export const GetV1SearchResponse$outboundSchema: z.ZodType<
  GetV1SearchResponse$Outbound,
  z.ZodTypeDef,
  GetV1SearchResponse
> = z.object({
  id: z.string(),
  type: z.string(),
  relevance: z.number(),
  createdAt: z.string(),
  data: z.nullable(z.any()).optional(),
}).transform((v) => {
  return remap$(v, {
    createdAt: "created_at",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetV1SearchResponse$ {
  /** @deprecated use `GetV1SearchResponse$inboundSchema` instead. */
  export const inboundSchema = GetV1SearchResponse$inboundSchema;
  /** @deprecated use `GetV1SearchResponse$outboundSchema` instead. */
  export const outboundSchema = GetV1SearchResponse$outboundSchema;
  /** @deprecated use `GetV1SearchResponse$Outbound` instead. */
  export type Outbound = GetV1SearchResponse$Outbound;
}

export function getV1SearchResponseToJSON(
  getV1SearchResponse: GetV1SearchResponse,
): string {
  return JSON.stringify(
    GetV1SearchResponse$outboundSchema.parse(getV1SearchResponse),
  );
}

export function getV1SearchResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetV1SearchResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1SearchResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1SearchResponse' from JSON`,
  );
}
