/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetV1MetricsProfitRequest = {
  from: string;
  to: string;
  currency?: string | undefined;
};

/** @internal */
export const GetV1MetricsProfitRequest$inboundSchema: z.ZodType<
  GetV1MetricsProfitRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  from: z.string(),
  to: z.string(),
  currency: z.string().optional(),
});

/** @internal */
export type GetV1MetricsProfitRequest$Outbound = {
  from: string;
  to: string;
  currency?: string | undefined;
};

/** @internal */
export const GetV1MetricsProfitRequest$outboundSchema: z.ZodType<
  GetV1MetricsProfitRequest$Outbound,
  z.ZodTypeDef,
  GetV1MetricsProfitRequest
> = z.object({
  from: z.string(),
  to: z.string(),
  currency: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetV1MetricsProfitRequest$ {
  /** @deprecated use `GetV1MetricsProfitRequest$inboundSchema` instead. */
  export const inboundSchema = GetV1MetricsProfitRequest$inboundSchema;
  /** @deprecated use `GetV1MetricsProfitRequest$outboundSchema` instead. */
  export const outboundSchema = GetV1MetricsProfitRequest$outboundSchema;
  /** @deprecated use `GetV1MetricsProfitRequest$Outbound` instead. */
  export type Outbound = GetV1MetricsProfitRequest$Outbound;
}

export function getV1MetricsProfitRequestToJSON(
  getV1MetricsProfitRequest: GetV1MetricsProfitRequest,
): string {
  return JSON.stringify(
    GetV1MetricsProfitRequest$outboundSchema.parse(getV1MetricsProfitRequest),
  );
}

export function getV1MetricsProfitRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetV1MetricsProfitRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1MetricsProfitRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1MetricsProfitRequest' from JSON`,
  );
}
