/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetV1MetricsRunwayRequest = {
  from: string;
  to: string;
  currency?: string | undefined;
};

/** @internal */
export const GetV1MetricsRunwayRequest$inboundSchema: z.ZodType<
  GetV1MetricsRunwayRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  from: z.string(),
  to: z.string(),
  currency: z.string().optional(),
});

/** @internal */
export type GetV1MetricsRunwayRequest$Outbound = {
  from: string;
  to: string;
  currency?: string | undefined;
};

/** @internal */
export const GetV1MetricsRunwayRequest$outboundSchema: z.ZodType<
  GetV1MetricsRunwayRequest$Outbound,
  z.ZodTypeDef,
  GetV1MetricsRunwayRequest
> = z.object({
  from: z.string(),
  to: z.string(),
  currency: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetV1MetricsRunwayRequest$ {
  /** @deprecated use `GetV1MetricsRunwayRequest$inboundSchema` instead. */
  export const inboundSchema = GetV1MetricsRunwayRequest$inboundSchema;
  /** @deprecated use `GetV1MetricsRunwayRequest$outboundSchema` instead. */
  export const outboundSchema = GetV1MetricsRunwayRequest$outboundSchema;
  /** @deprecated use `GetV1MetricsRunwayRequest$Outbound` instead. */
  export type Outbound = GetV1MetricsRunwayRequest$Outbound;
}

export function getV1MetricsRunwayRequestToJSON(
  getV1MetricsRunwayRequest: GetV1MetricsRunwayRequest,
): string {
  return JSON.stringify(
    GetV1MetricsRunwayRequest$outboundSchema.parse(getV1MetricsRunwayRequest),
  );
}

export function getV1MetricsRunwayRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetV1MetricsRunwayRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1MetricsRunwayRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1MetricsRunwayRequest' from JSON`,
  );
}
