/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetV1MetricsSpendingRequest = {
  from: string;
  to: string;
  currency?: string | undefined;
};

/** @internal */
export const GetV1MetricsSpendingRequest$inboundSchema: z.ZodType<
  GetV1MetricsSpendingRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  from: z.string(),
  to: z.string(),
  currency: z.string().optional(),
});

/** @internal */
export type GetV1MetricsSpendingRequest$Outbound = {
  from: string;
  to: string;
  currency?: string | undefined;
};

/** @internal */
export const GetV1MetricsSpendingRequest$outboundSchema: z.ZodType<
  GetV1MetricsSpendingRequest$Outbound,
  z.ZodTypeDef,
  GetV1MetricsSpendingRequest
> = z.object({
  from: z.string(),
  to: z.string(),
  currency: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetV1MetricsSpendingRequest$ {
  /** @deprecated use `GetV1MetricsSpendingRequest$inboundSchema` instead. */
  export const inboundSchema = GetV1MetricsSpendingRequest$inboundSchema;
  /** @deprecated use `GetV1MetricsSpendingRequest$outboundSchema` instead. */
  export const outboundSchema = GetV1MetricsSpendingRequest$outboundSchema;
  /** @deprecated use `GetV1MetricsSpendingRequest$Outbound` instead. */
  export type Outbound = GetV1MetricsSpendingRequest$Outbound;
}

export function getV1MetricsSpendingRequestToJSON(
  getV1MetricsSpendingRequest: GetV1MetricsSpendingRequest,
): string {
  return JSON.stringify(
    GetV1MetricsSpendingRequest$outboundSchema.parse(
      getV1MetricsSpendingRequest,
    ),
  );
}

export function getV1MetricsSpendingRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetV1MetricsSpendingRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetV1MetricsSpendingRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetV1MetricsSpendingRequest' from JSON`,
  );
}
