/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type ErrorT = {
  path: string;
  message: string;
};

/**
 * Webhook processed successfully
 */
export type InboxWebhookResponse = {
  success: boolean;
};

/** @internal */
export const ErrorT$inboundSchema: z.ZodType<ErrorT, z.ZodTypeDef, unknown> = z
  .object({
    path: z.string(),
    message: z.string(),
  });
/** @internal */
export type ErrorT$Outbound = {
  path: string;
  message: string;
};

/** @internal */
export const ErrorT$outboundSchema: z.ZodType<
  ErrorT$Outbound,
  z.ZodTypeDef,
  ErrorT
> = z.object({
  path: z.string(),
  message: z.string(),
});

export function errorToJSON(errorT: ErrorT): string {
  return JSON.stringify(ErrorT$outboundSchema.parse(errorT));
}
export function errorFromJSON(
  jsonString: string,
): SafeParseResult<ErrorT, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ErrorT$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ErrorT' from JSON`,
  );
}

/** @internal */
export const InboxWebhookResponse$inboundSchema: z.ZodType<
  InboxWebhookResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  success: z.boolean(),
});
/** @internal */
export type InboxWebhookResponse$Outbound = {
  success: boolean;
};

/** @internal */
export const InboxWebhookResponse$outboundSchema: z.ZodType<
  InboxWebhookResponse$Outbound,
  z.ZodTypeDef,
  InboxWebhookResponse
> = z.object({
  success: z.boolean(),
});

export function inboxWebhookResponseToJSON(
  inboxWebhookResponse: InboxWebhookResponse,
): string {
  return JSON.stringify(
    InboxWebhookResponse$outboundSchema.parse(inboxWebhookResponse),
  );
}
export function inboxWebhookResponseFromJSON(
  jsonString: string,
): SafeParseResult<InboxWebhookResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => InboxWebhookResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'InboxWebhookResponse' from JSON`,
  );
}
