/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

/**
 * Filter transactions based on attachment presence. 'include' returns only transactions with attachments, 'exclude' returns only transactions without attachments
 */
export const Attachments = {
  Include: "include",
  Exclude: "exclude",
} as const;
/**
 * Filter transactions based on attachment presence. 'include' returns only transactions with attachments, 'exclude' returns only transactions without attachments
 */
export type Attachments = ClosedEnum<typeof Attachments>;

/**
 * Transaction type to filter by. 'income' for money received, 'expense' for money spent
 */
export const ListTransactionsType = {
  Income: "income",
  Expense: "expense",
} as const;
/**
 * Transaction type to filter by. 'income' for money received, 'expense' for money spent
 */
export type ListTransactionsType = ClosedEnum<typeof ListTransactionsType>;

/**
 * Filter transactions based on whether they were manually imported. 'include' returns only manual transactions, 'exclude' returns only non-manual transactions
 */
export const Manual = {
  Include: "include",
  Exclude: "exclude",
} as const;
/**
 * Filter transactions based on whether they were manually imported. 'include' returns only manual transactions, 'exclude' returns only non-manual transactions
 */
export type Manual = ClosedEnum<typeof Manual>;

export type ListTransactionsRequest = {
  /**
   * Cursor for pagination, representing the last item from the previous page
   */
  cursor?: string | null | undefined;
  /**
   * Sorting order as a tuple: [field, direction]. Example: ['date', 'desc'] or ['amount', 'asc']
   */
  sort?: Array<string> | null | undefined;
  /**
   * Number of transactions to return per page (1-10000)
   */
  pageSize?: number | undefined;
  /**
   * Search query string to filter transactions by name, description, or other text fields
   */
  q?: string | null | undefined;
  /**
   * Array of category slugs to filter transactions by specific categories
   */
  categories?: Array<string> | null | undefined;
  /**
   * Array of tag IDs to filter transactions by specific tags
   */
  tags?: Array<string> | null | undefined;
  /**
   * Start date (inclusive) for filtering transactions in ISO 8601 format
   */
  start?: string | null | undefined;
  /**
   * End date (inclusive) for filtering transactions in ISO 8601 format
   */
  end?: string | null | undefined;
  /**
   * Array of bank account IDs to filter transactions by specific accounts
   */
  accounts?: Array<string> | null | undefined;
  /**
   * Array of user IDs to filter transactions by assigned users
   */
  assignees?: Array<string> | null | undefined;
  /**
   * Array of transaction statuses to filter by. Available statuses: 'pending', 'completed', 'archived', 'posted', 'excluded'
   */
  statuses?: Array<string> | null | undefined;
  /**
   * Array of recurring frequency values to filter by. Available frequencies: 'weekly', 'monthly', 'annually', 'irregular'
   */
  recurring?: Array<string> | null | undefined;
  /**
   * Filter transactions based on attachment presence. 'include' returns only transactions with attachments, 'exclude' returns only transactions without attachments
   */
  attachments?: Attachments | null | undefined;
  /**
   * Amount range as [min, max] to filter transactions by monetary value
   */
  amountRange?: Array<number | null> | null | undefined;
  /**
   * Array of specific amounts (as strings) to filter transactions by exact values
   */
  amount?: Array<string> | null | undefined;
  /**
   * Transaction type to filter by. 'income' for money received, 'expense' for money spent
   */
  type?: ListTransactionsType | null | undefined;
  /**
   * Filter transactions based on whether they were manually imported. 'include' returns only manual transactions, 'exclude' returns only non-manual transactions
   */
  manual?: Manual | null | undefined;
  /**
   * Filter by export status. true = only exported transactions, false = only NOT exported transactions, undefined = no filter
   */
  exported?: boolean | null | undefined;
  /**
   * Filter by fulfillment status. true = transactions ready for review (has attachments OR status=completed), false = not ready, undefined = no filter
   */
  fulfilled?: boolean | null | undefined;
};

/**
 * Pagination metadata for the transactions response
 */
export type ListTransactionsMeta = {
  /**
   * Cursor for the next page of results, undefined if no more pages
   */
  cursor?: string | undefined;
  /**
   * Whether there are more transactions available on the previous page
   */
  hasPreviousPage: boolean;
  /**
   * Whether there are more transactions available on the next page
   */
  hasNextPage: boolean;
};

/**
 * Retrieve a list of transactions for the authenticated team.
 */
export type ListTransactionsResponse = {
  /**
   * Pagination metadata for the transactions response
   */
  meta: ListTransactionsMeta;
  /**
   * Array of transactions matching the query criteria
   */
  data: Array<models.TransactionResponse>;
};

/** @internal */
export const Attachments$inboundSchema: z.ZodNativeEnum<typeof Attachments> = z
  .nativeEnum(Attachments);
/** @internal */
export const Attachments$outboundSchema: z.ZodNativeEnum<typeof Attachments> =
  Attachments$inboundSchema;

/** @internal */
export const ListTransactionsType$inboundSchema: z.ZodNativeEnum<
  typeof ListTransactionsType
> = z.nativeEnum(ListTransactionsType);
/** @internal */
export const ListTransactionsType$outboundSchema: z.ZodNativeEnum<
  typeof ListTransactionsType
> = ListTransactionsType$inboundSchema;

/** @internal */
export const Manual$inboundSchema: z.ZodNativeEnum<typeof Manual> = z
  .nativeEnum(Manual);
/** @internal */
export const Manual$outboundSchema: z.ZodNativeEnum<typeof Manual> =
  Manual$inboundSchema;

/** @internal */
export const ListTransactionsRequest$inboundSchema: z.ZodType<
  ListTransactionsRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  cursor: z.nullable(z.string()).optional(),
  sort: z.nullable(z.array(z.string())).optional(),
  pageSize: z.number().optional(),
  q: z.nullable(z.string()).optional(),
  categories: z.nullable(z.array(z.string())).optional(),
  tags: z.nullable(z.array(z.string())).optional(),
  start: z.nullable(z.string()).optional(),
  end: z.nullable(z.string()).optional(),
  accounts: z.nullable(z.array(z.string())).optional(),
  assignees: z.nullable(z.array(z.string())).optional(),
  statuses: z.nullable(z.array(z.string())).optional(),
  recurring: z.nullable(z.array(z.string())).optional(),
  attachments: z.nullable(Attachments$inboundSchema).optional(),
  amountRange: z.nullable(z.array(z.nullable(z.number()))).optional(),
  amount: z.nullable(z.array(z.string())).optional(),
  type: z.nullable(ListTransactionsType$inboundSchema).optional(),
  manual: z.nullable(Manual$inboundSchema).optional(),
  exported: z.nullable(z.boolean()).optional(),
  fulfilled: z.nullable(z.boolean()).optional(),
});
/** @internal */
export type ListTransactionsRequest$Outbound = {
  cursor?: string | null | undefined;
  sort?: Array<string> | null | undefined;
  pageSize?: number | undefined;
  q?: string | null | undefined;
  categories?: Array<string> | null | undefined;
  tags?: Array<string> | null | undefined;
  start?: string | null | undefined;
  end?: string | null | undefined;
  accounts?: Array<string> | null | undefined;
  assignees?: Array<string> | null | undefined;
  statuses?: Array<string> | null | undefined;
  recurring?: Array<string> | null | undefined;
  attachments?: string | null | undefined;
  amountRange?: Array<number | null> | null | undefined;
  amount?: Array<string> | null | undefined;
  type?: string | null | undefined;
  manual?: string | null | undefined;
  exported?: boolean | null | undefined;
  fulfilled?: boolean | null | undefined;
};

/** @internal */
export const ListTransactionsRequest$outboundSchema: z.ZodType<
  ListTransactionsRequest$Outbound,
  z.ZodTypeDef,
  ListTransactionsRequest
> = z.object({
  cursor: z.nullable(z.string()).optional(),
  sort: z.nullable(z.array(z.string())).optional(),
  pageSize: z.number().optional(),
  q: z.nullable(z.string()).optional(),
  categories: z.nullable(z.array(z.string())).optional(),
  tags: z.nullable(z.array(z.string())).optional(),
  start: z.nullable(z.string()).optional(),
  end: z.nullable(z.string()).optional(),
  accounts: z.nullable(z.array(z.string())).optional(),
  assignees: z.nullable(z.array(z.string())).optional(),
  statuses: z.nullable(z.array(z.string())).optional(),
  recurring: z.nullable(z.array(z.string())).optional(),
  attachments: z.nullable(Attachments$outboundSchema).optional(),
  amountRange: z.nullable(z.array(z.nullable(z.number()))).optional(),
  amount: z.nullable(z.array(z.string())).optional(),
  type: z.nullable(ListTransactionsType$outboundSchema).optional(),
  manual: z.nullable(Manual$outboundSchema).optional(),
  exported: z.nullable(z.boolean()).optional(),
  fulfilled: z.nullable(z.boolean()).optional(),
});

export function listTransactionsRequestToJSON(
  listTransactionsRequest: ListTransactionsRequest,
): string {
  return JSON.stringify(
    ListTransactionsRequest$outboundSchema.parse(listTransactionsRequest),
  );
}
export function listTransactionsRequestFromJSON(
  jsonString: string,
): SafeParseResult<ListTransactionsRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListTransactionsRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListTransactionsRequest' from JSON`,
  );
}

/** @internal */
export const ListTransactionsMeta$inboundSchema: z.ZodType<
  ListTransactionsMeta,
  z.ZodTypeDef,
  unknown
> = z.object({
  cursor: z.string().optional(),
  hasPreviousPage: z.boolean(),
  hasNextPage: z.boolean(),
});
/** @internal */
export type ListTransactionsMeta$Outbound = {
  cursor?: string | undefined;
  hasPreviousPage: boolean;
  hasNextPage: boolean;
};

/** @internal */
export const ListTransactionsMeta$outboundSchema: z.ZodType<
  ListTransactionsMeta$Outbound,
  z.ZodTypeDef,
  ListTransactionsMeta
> = z.object({
  cursor: z.string().optional(),
  hasPreviousPage: z.boolean(),
  hasNextPage: z.boolean(),
});

export function listTransactionsMetaToJSON(
  listTransactionsMeta: ListTransactionsMeta,
): string {
  return JSON.stringify(
    ListTransactionsMeta$outboundSchema.parse(listTransactionsMeta),
  );
}
export function listTransactionsMetaFromJSON(
  jsonString: string,
): SafeParseResult<ListTransactionsMeta, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListTransactionsMeta$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListTransactionsMeta' from JSON`,
  );
}

/** @internal */
export const ListTransactionsResponse$inboundSchema: z.ZodType<
  ListTransactionsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  meta: z.lazy(() => ListTransactionsMeta$inboundSchema),
  data: z.array(models.TransactionResponse$inboundSchema),
});
/** @internal */
export type ListTransactionsResponse$Outbound = {
  meta: ListTransactionsMeta$Outbound;
  data: Array<models.TransactionResponse$Outbound>;
};

/** @internal */
export const ListTransactionsResponse$outboundSchema: z.ZodType<
  ListTransactionsResponse$Outbound,
  z.ZodTypeDef,
  ListTransactionsResponse
> = z.object({
  meta: z.lazy(() => ListTransactionsMeta$outboundSchema),
  data: z.array(models.TransactionResponse$outboundSchema),
});

export function listTransactionsResponseToJSON(
  listTransactionsResponse: ListTransactionsResponse,
): string {
  return JSON.stringify(
    ListTransactionsResponse$outboundSchema.parse(listTransactionsResponse),
  );
}
export function listTransactionsResponseFromJSON(
  jsonString: string,
): SafeParseResult<ListTransactionsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => ListTransactionsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'ListTransactionsResponse' from JSON`,
  );
}
