/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Webhook processed successfully
 */
export type PolarWebhookResponse = {
  received: boolean;
};

/** @internal */
export const PolarWebhookResponse$inboundSchema: z.ZodType<
  PolarWebhookResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  received: z.boolean(),
});

/** @internal */
export type PolarWebhookResponse$Outbound = {
  received: boolean;
};

/** @internal */
export const PolarWebhookResponse$outboundSchema: z.ZodType<
  PolarWebhookResponse$Outbound,
  z.ZodTypeDef,
  PolarWebhookResponse
> = z.object({
  received: z.boolean(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace PolarWebhookResponse$ {
  /** @deprecated use `PolarWebhookResponse$inboundSchema` instead. */
  export const inboundSchema = PolarWebhookResponse$inboundSchema;
  /** @deprecated use `PolarWebhookResponse$outboundSchema` instead. */
  export const outboundSchema = PolarWebhookResponse$outboundSchema;
  /** @deprecated use `PolarWebhookResponse$Outbound` instead. */
  export type Outbound = PolarWebhookResponse$Outbound;
}

export function polarWebhookResponseToJSON(
  polarWebhookResponse: PolarWebhookResponse,
): string {
  return JSON.stringify(
    PolarWebhookResponse$outboundSchema.parse(polarWebhookResponse),
  );
}

export function polarWebhookResponseFromJSON(
  jsonString: string,
): SafeParseResult<PolarWebhookResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => PolarWebhookResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'PolarWebhookResponse' from JSON`,
  );
}
