/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Webhook processed successfully
 */
export type SlackWebhookResponse = {
  challenge?: string | undefined;
  ok?: boolean | undefined;
};

/** @internal */
export const SlackWebhookResponse$inboundSchema: z.ZodType<
  SlackWebhookResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  challenge: z.string().optional(),
  ok: z.boolean().optional(),
});
/** @internal */
export type SlackWebhookResponse$Outbound = {
  challenge?: string | undefined;
  ok?: boolean | undefined;
};

/** @internal */
export const SlackWebhookResponse$outboundSchema: z.ZodType<
  SlackWebhookResponse$Outbound,
  z.ZodTypeDef,
  SlackWebhookResponse
> = z.object({
  challenge: z.string().optional(),
  ok: z.boolean().optional(),
});

export function slackWebhookResponseToJSON(
  slackWebhookResponse: SlackWebhookResponse,
): string {
  return JSON.stringify(
    SlackWebhookResponse$outboundSchema.parse(slackWebhookResponse),
  );
}
export function slackWebhookResponseFromJSON(
  jsonString: string,
): SafeParseResult<SlackWebhookResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SlackWebhookResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SlackWebhookResponse' from JSON`,
  );
}
