/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod/v3";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

/**
 * Interaction handled successfully
 */
export type SlackInteractionsResponse = {
  ok: boolean;
};

/** @internal */
export const SlackInteractionsResponse$inboundSchema: z.ZodType<
  SlackInteractionsResponse,
  z.ZodTypeDef,
  unknown
> = z.object({
  ok: z.boolean(),
});
/** @internal */
export type SlackInteractionsResponse$Outbound = {
  ok: boolean;
};

/** @internal */
export const SlackInteractionsResponse$outboundSchema: z.ZodType<
  SlackInteractionsResponse$Outbound,
  z.ZodTypeDef,
  SlackInteractionsResponse
> = z.object({
  ok: z.boolean(),
});

export function slackInteractionsResponseToJSON(
  slackInteractionsResponse: SlackInteractionsResponse,
): string {
  return JSON.stringify(
    SlackInteractionsResponse$outboundSchema.parse(slackInteractionsResponse),
  );
}
export function slackInteractionsResponseFromJSON(
  jsonString: string,
): SafeParseResult<SlackInteractionsResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => SlackInteractionsResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'SlackInteractionsResponse' from JSON`,
  );
}
