/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

export type UpdateTagRequestBody = {
  /**
   * The new name of the tag.
   */
  name: string;
};

export type UpdateTagRequest = {
  /**
   * The ID of the tag to update.
   */
  id: string;
  requestBody: UpdateTagRequestBody;
};

export type UpdateTagResponse = models.TagResponse | models.ErrorResponse;

/** @internal */
export const UpdateTagRequestBody$inboundSchema: z.ZodType<
  UpdateTagRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string(),
});

/** @internal */
export type UpdateTagRequestBody$Outbound = {
  name: string;
};

/** @internal */
export const UpdateTagRequestBody$outboundSchema: z.ZodType<
  UpdateTagRequestBody$Outbound,
  z.ZodTypeDef,
  UpdateTagRequestBody
> = z.object({
  name: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateTagRequestBody$ {
  /** @deprecated use `UpdateTagRequestBody$inboundSchema` instead. */
  export const inboundSchema = UpdateTagRequestBody$inboundSchema;
  /** @deprecated use `UpdateTagRequestBody$outboundSchema` instead. */
  export const outboundSchema = UpdateTagRequestBody$outboundSchema;
  /** @deprecated use `UpdateTagRequestBody$Outbound` instead. */
  export type Outbound = UpdateTagRequestBody$Outbound;
}

export function updateTagRequestBodyToJSON(
  updateTagRequestBody: UpdateTagRequestBody,
): string {
  return JSON.stringify(
    UpdateTagRequestBody$outboundSchema.parse(updateTagRequestBody),
  );
}

export function updateTagRequestBodyFromJSON(
  jsonString: string,
): SafeParseResult<UpdateTagRequestBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateTagRequestBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateTagRequestBody' from JSON`,
  );
}

/** @internal */
export const UpdateTagRequest$inboundSchema: z.ZodType<
  UpdateTagRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  RequestBody: z.lazy(() => UpdateTagRequestBody$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "RequestBody": "requestBody",
  });
});

/** @internal */
export type UpdateTagRequest$Outbound = {
  id: string;
  RequestBody: UpdateTagRequestBody$Outbound;
};

/** @internal */
export const UpdateTagRequest$outboundSchema: z.ZodType<
  UpdateTagRequest$Outbound,
  z.ZodTypeDef,
  UpdateTagRequest
> = z.object({
  id: z.string(),
  requestBody: z.lazy(() => UpdateTagRequestBody$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    requestBody: "RequestBody",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateTagRequest$ {
  /** @deprecated use `UpdateTagRequest$inboundSchema` instead. */
  export const inboundSchema = UpdateTagRequest$inboundSchema;
  /** @deprecated use `UpdateTagRequest$outboundSchema` instead. */
  export const outboundSchema = UpdateTagRequest$outboundSchema;
  /** @deprecated use `UpdateTagRequest$Outbound` instead. */
  export type Outbound = UpdateTagRequest$Outbound;
}

export function updateTagRequestToJSON(
  updateTagRequest: UpdateTagRequest,
): string {
  return JSON.stringify(
    UpdateTagRequest$outboundSchema.parse(updateTagRequest),
  );
}

export function updateTagRequestFromJSON(
  jsonString: string,
): SafeParseResult<UpdateTagRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateTagRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateTagRequest' from JSON`,
  );
}

/** @internal */
export const UpdateTagResponse$inboundSchema: z.ZodType<
  UpdateTagResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  models.TagResponse$inboundSchema,
  models.ErrorResponse$inboundSchema,
]);

/** @internal */
export type UpdateTagResponse$Outbound =
  | models.TagResponse$Outbound
  | models.ErrorResponse$Outbound;

/** @internal */
export const UpdateTagResponse$outboundSchema: z.ZodType<
  UpdateTagResponse$Outbound,
  z.ZodTypeDef,
  UpdateTagResponse
> = z.union([
  models.TagResponse$outboundSchema,
  models.ErrorResponse$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateTagResponse$ {
  /** @deprecated use `UpdateTagResponse$inboundSchema` instead. */
  export const inboundSchema = UpdateTagResponse$inboundSchema;
  /** @deprecated use `UpdateTagResponse$outboundSchema` instead. */
  export const outboundSchema = UpdateTagResponse$outboundSchema;
  /** @deprecated use `UpdateTagResponse$Outbound` instead. */
  export type Outbound = UpdateTagResponse$Outbound;
}

export function updateTagResponseToJSON(
  updateTagResponse: UpdateTagResponse,
): string {
  return JSON.stringify(
    UpdateTagResponse$outboundSchema.parse(updateTagResponse),
  );
}

export function updateTagResponseFromJSON(
  jsonString: string,
): SafeParseResult<UpdateTagResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateTagResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateTagResponse' from JSON`,
  );
}
