/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { remap as remap$ } from "../../lib/primitives.js";
import { safeParse } from "../../lib/schemas.js";
import { ClosedEnum } from "../../types/enums.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";
import * as models from "../index.js";

/**
 * Status of the transaction.
 */
export const UpdateTransactionStatus = {
  Pending: "pending",
  Archived: "archived",
  Completed: "completed",
  Posted: "posted",
  Excluded: "excluded",
  Exported: "exported",
} as const;
/**
 * Status of the transaction.
 */
export type UpdateTransactionStatus = ClosedEnum<
  typeof UpdateTransactionStatus
>;

/**
 * Recurring frequency of the transaction.
 */
export const UpdateTransactionFrequency = {
  Weekly: "weekly",
  Monthly: "monthly",
  Annually: "annually",
  Irregular: "irregular",
} as const;
/**
 * Recurring frequency of the transaction.
 */
export type UpdateTransactionFrequency = ClosedEnum<
  typeof UpdateTransactionFrequency
>;

export type UpdateTransactionRequestBody = {
  /**
   * Name/description of the transaction.
   */
  name?: string | undefined;
  /**
   * Amount of the transaction.
   */
  amount?: number | undefined;
  /**
   * Currency of the transaction.
   */
  currency?: string | undefined;
  /**
   * Date of the transaction (ISO 8601).
   */
  date?: string | undefined;
  /**
   * Bank account ID associated with the transaction.
   */
  bankAccountId?: string | undefined;
  /**
   * Category slug for the transaction.
   */
  categorySlug?: string | null | undefined;
  /**
   * Status of the transaction.
   */
  status?: UpdateTransactionStatus | null | undefined;
  /**
   * Whether the transaction is internal.
   */
  internal?: boolean | undefined;
  /**
   * Whether the transaction is recurring.
   */
  recurring?: boolean | undefined;
  /**
   * Recurring frequency of the transaction.
   */
  frequency?: UpdateTransactionFrequency | null | undefined;
  /**
   * Note for the transaction.
   */
  note?: string | null | undefined;
  /**
   * Assigned user ID for the transaction.
   */
  assignedId?: string | null | undefined;
  /**
   * Tax rate as a percentage (e.g., 25 for 25% VAT). Only set when tax is calculated from a percentage.
   */
  taxRate?: number | null | undefined;
  /**
   * Tax amount in the transaction currency. Always set when tax is present.
   */
  taxAmount?: number | null | undefined;
};

export type UpdateTransactionRequest = {
  /**
   * Transaction ID (UUID).
   */
  id: string;
  requestBody: UpdateTransactionRequestBody;
};

export type UpdateTransactionResponse =
  | models.TransactionResponse
  | models.ErrorResponse;

/** @internal */
export const UpdateTransactionStatus$inboundSchema: z.ZodNativeEnum<
  typeof UpdateTransactionStatus
> = z.nativeEnum(UpdateTransactionStatus);

/** @internal */
export const UpdateTransactionStatus$outboundSchema: z.ZodNativeEnum<
  typeof UpdateTransactionStatus
> = UpdateTransactionStatus$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateTransactionStatus$ {
  /** @deprecated use `UpdateTransactionStatus$inboundSchema` instead. */
  export const inboundSchema = UpdateTransactionStatus$inboundSchema;
  /** @deprecated use `UpdateTransactionStatus$outboundSchema` instead. */
  export const outboundSchema = UpdateTransactionStatus$outboundSchema;
}

/** @internal */
export const UpdateTransactionFrequency$inboundSchema: z.ZodNativeEnum<
  typeof UpdateTransactionFrequency
> = z.nativeEnum(UpdateTransactionFrequency);

/** @internal */
export const UpdateTransactionFrequency$outboundSchema: z.ZodNativeEnum<
  typeof UpdateTransactionFrequency
> = UpdateTransactionFrequency$inboundSchema;

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateTransactionFrequency$ {
  /** @deprecated use `UpdateTransactionFrequency$inboundSchema` instead. */
  export const inboundSchema = UpdateTransactionFrequency$inboundSchema;
  /** @deprecated use `UpdateTransactionFrequency$outboundSchema` instead. */
  export const outboundSchema = UpdateTransactionFrequency$outboundSchema;
}

/** @internal */
export const UpdateTransactionRequestBody$inboundSchema: z.ZodType<
  UpdateTransactionRequestBody,
  z.ZodTypeDef,
  unknown
> = z.object({
  name: z.string().optional(),
  amount: z.number().optional(),
  currency: z.string().optional(),
  date: z.string().optional(),
  bankAccountId: z.string().optional(),
  categorySlug: z.nullable(z.string()).optional(),
  status: z.nullable(UpdateTransactionStatus$inboundSchema).optional(),
  internal: z.boolean().optional(),
  recurring: z.boolean().optional(),
  frequency: z.nullable(UpdateTransactionFrequency$inboundSchema).optional(),
  note: z.nullable(z.string()).optional(),
  assignedId: z.nullable(z.string()).optional(),
  taxRate: z.nullable(z.number()).optional(),
  taxAmount: z.nullable(z.number()).optional(),
});

/** @internal */
export type UpdateTransactionRequestBody$Outbound = {
  name?: string | undefined;
  amount?: number | undefined;
  currency?: string | undefined;
  date?: string | undefined;
  bankAccountId?: string | undefined;
  categorySlug?: string | null | undefined;
  status?: string | null | undefined;
  internal?: boolean | undefined;
  recurring?: boolean | undefined;
  frequency?: string | null | undefined;
  note?: string | null | undefined;
  assignedId?: string | null | undefined;
  taxRate?: number | null | undefined;
  taxAmount?: number | null | undefined;
};

/** @internal */
export const UpdateTransactionRequestBody$outboundSchema: z.ZodType<
  UpdateTransactionRequestBody$Outbound,
  z.ZodTypeDef,
  UpdateTransactionRequestBody
> = z.object({
  name: z.string().optional(),
  amount: z.number().optional(),
  currency: z.string().optional(),
  date: z.string().optional(),
  bankAccountId: z.string().optional(),
  categorySlug: z.nullable(z.string()).optional(),
  status: z.nullable(UpdateTransactionStatus$outboundSchema).optional(),
  internal: z.boolean().optional(),
  recurring: z.boolean().optional(),
  frequency: z.nullable(UpdateTransactionFrequency$outboundSchema).optional(),
  note: z.nullable(z.string()).optional(),
  assignedId: z.nullable(z.string()).optional(),
  taxRate: z.nullable(z.number()).optional(),
  taxAmount: z.nullable(z.number()).optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateTransactionRequestBody$ {
  /** @deprecated use `UpdateTransactionRequestBody$inboundSchema` instead. */
  export const inboundSchema = UpdateTransactionRequestBody$inboundSchema;
  /** @deprecated use `UpdateTransactionRequestBody$outboundSchema` instead. */
  export const outboundSchema = UpdateTransactionRequestBody$outboundSchema;
  /** @deprecated use `UpdateTransactionRequestBody$Outbound` instead. */
  export type Outbound = UpdateTransactionRequestBody$Outbound;
}

export function updateTransactionRequestBodyToJSON(
  updateTransactionRequestBody: UpdateTransactionRequestBody,
): string {
  return JSON.stringify(
    UpdateTransactionRequestBody$outboundSchema.parse(
      updateTransactionRequestBody,
    ),
  );
}

export function updateTransactionRequestBodyFromJSON(
  jsonString: string,
): SafeParseResult<UpdateTransactionRequestBody, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateTransactionRequestBody$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateTransactionRequestBody' from JSON`,
  );
}

/** @internal */
export const UpdateTransactionRequest$inboundSchema: z.ZodType<
  UpdateTransactionRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  id: z.string(),
  RequestBody: z.lazy(() => UpdateTransactionRequestBody$inboundSchema),
}).transform((v) => {
  return remap$(v, {
    "RequestBody": "requestBody",
  });
});

/** @internal */
export type UpdateTransactionRequest$Outbound = {
  id: string;
  RequestBody: UpdateTransactionRequestBody$Outbound;
};

/** @internal */
export const UpdateTransactionRequest$outboundSchema: z.ZodType<
  UpdateTransactionRequest$Outbound,
  z.ZodTypeDef,
  UpdateTransactionRequest
> = z.object({
  id: z.string(),
  requestBody: z.lazy(() => UpdateTransactionRequestBody$outboundSchema),
}).transform((v) => {
  return remap$(v, {
    requestBody: "RequestBody",
  });
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateTransactionRequest$ {
  /** @deprecated use `UpdateTransactionRequest$inboundSchema` instead. */
  export const inboundSchema = UpdateTransactionRequest$inboundSchema;
  /** @deprecated use `UpdateTransactionRequest$outboundSchema` instead. */
  export const outboundSchema = UpdateTransactionRequest$outboundSchema;
  /** @deprecated use `UpdateTransactionRequest$Outbound` instead. */
  export type Outbound = UpdateTransactionRequest$Outbound;
}

export function updateTransactionRequestToJSON(
  updateTransactionRequest: UpdateTransactionRequest,
): string {
  return JSON.stringify(
    UpdateTransactionRequest$outboundSchema.parse(updateTransactionRequest),
  );
}

export function updateTransactionRequestFromJSON(
  jsonString: string,
): SafeParseResult<UpdateTransactionRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateTransactionRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateTransactionRequest' from JSON`,
  );
}

/** @internal */
export const UpdateTransactionResponse$inboundSchema: z.ZodType<
  UpdateTransactionResponse,
  z.ZodTypeDef,
  unknown
> = z.union([
  models.TransactionResponse$inboundSchema,
  models.ErrorResponse$inboundSchema,
]);

/** @internal */
export type UpdateTransactionResponse$Outbound =
  | models.TransactionResponse$Outbound
  | models.ErrorResponse$Outbound;

/** @internal */
export const UpdateTransactionResponse$outboundSchema: z.ZodType<
  UpdateTransactionResponse$Outbound,
  z.ZodTypeDef,
  UpdateTransactionResponse
> = z.union([
  models.TransactionResponse$outboundSchema,
  models.ErrorResponse$outboundSchema,
]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdateTransactionResponse$ {
  /** @deprecated use `UpdateTransactionResponse$inboundSchema` instead. */
  export const inboundSchema = UpdateTransactionResponse$inboundSchema;
  /** @deprecated use `UpdateTransactionResponse$outboundSchema` instead. */
  export const outboundSchema = UpdateTransactionResponse$outboundSchema;
  /** @deprecated use `UpdateTransactionResponse$Outbound` instead. */
  export type Outbound = UpdateTransactionResponse$Outbound;
}

export function updateTransactionResponseToJSON(
  updateTransactionResponse: UpdateTransactionResponse,
): string {
  return JSON.stringify(
    UpdateTransactionResponse$outboundSchema.parse(updateTransactionResponse),
  );
}

export function updateTransactionResponseFromJSON(
  jsonString: string,
): SafeParseResult<UpdateTransactionResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdateTransactionResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdateTransactionResponse' from JSON`,
  );
}
