/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { safeParse } from "../lib/schemas.js";
import { Result as SafeParseResult } from "../types/fp.js";
import { SDKValidationError } from "./errors/sdkvalidationerror.js";

export type BurnRateItem = {
  /**
   * Date for the burn rate value
   */
  date: string;
  /**
   * Burn rate value for the given date
   */
  value: number;
  /**
   * Currency code (ISO 4217)
   */
  currency: string;
};

/** @internal */
export const BurnRateItem$inboundSchema: z.ZodType<
  BurnRateItem,
  z.ZodTypeDef,
  unknown
> = z.object({
  date: z.string(),
  value: z.number(),
  currency: z.string(),
});

/** @internal */
export type BurnRateItem$Outbound = {
  date: string;
  value: number;
  currency: string;
};

/** @internal */
export const BurnRateItem$outboundSchema: z.ZodType<
  BurnRateItem$Outbound,
  z.ZodTypeDef,
  BurnRateItem
> = z.object({
  date: z.string(),
  value: z.number(),
  currency: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace BurnRateItem$ {
  /** @deprecated use `BurnRateItem$inboundSchema` instead. */
  export const inboundSchema = BurnRateItem$inboundSchema;
  /** @deprecated use `BurnRateItem$outboundSchema` instead. */
  export const outboundSchema = BurnRateItem$outboundSchema;
  /** @deprecated use `BurnRateItem$Outbound` instead. */
  export type Outbound = BurnRateItem$Outbound;
}

export function burnRateItemToJSON(burnRateItem: BurnRateItem): string {
  return JSON.stringify(BurnRateItem$outboundSchema.parse(burnRateItem));
}

export function burnRateItemFromJSON(
  jsonString: string,
): SafeParseResult<BurnRateItem, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => BurnRateItem$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'BurnRateItem' from JSON`,
  );
}
